fix: dynamic routing using cookies
Tencent/spring-cloud-tencent pull request #1097
Opened 2023-08-31 12:46 UTC by blankjee

## PR Type
Bugfix.

## Describe what this PR does for and how you did.
增加了对Cookie的支持

## Adding the issue link (#xxx) if possible.
fixes #1035

## Checklist

- [ ] Will pull request to branch of 2020.0.

2023-09-01 02:27 UTC, SkyeBeFreeman requested changes
还需补充此方法中对cookie的提取：
```com.tencent.cloud.common.util.expresstion.SpringWebExpressionLabelUtils#resolve(org.springframework.http.HttpRequest, java.util.Set<java.lang.String>)```

2023-09-01 07:02 UTC, blankjee commented
已补充！

2023-09-02 04:19 UTC, SkyeBeFreeman commented
按照这个文档配置项目代码风格检查，https://docs.spring.io/spring-cloud-build/docs/current/reference/html/index.html#_intellij_idea

2023-09-14 08:57 UTC, SkyeBeFreeman approved these changes

2023-09-14 09:01 UTC, merged