refactor:optimize the order and condition matching of service registration automatic configuration.
Tencent/spring-cloud-tencent pull request #1129
Opened 2023-09-20 14:56 UTC by hligaty

…stration automatic configuration.

## PR Type

Refactoring (no functional changes, no api changes).

## Describe what this PR does for and how you did.

服务注册自动配置有下面几个疑问：

1. @AutoConfigureAfter 中 AutoServiceRegistrationConfiguration.class 应该是无效的。解决：移除这个参数
2. PolarisServiceRegistry 定义需要在 ServiceRegistryAutoConfiguration 完成前执行。解决：添加 @AutoConfigureBefore
3. 判断是否进行注册服务的条件注解放在服务注册自动配置类上覆盖所有 bean 会更清晰？

## Adding the issue link (#xxx) if possible.

## Note

## Checklist

- [ ] Add information of this PR to CHANGELOG.md in root of project.
- [ ] Add documentation in javadoc or comment below the PR if necessary.

## Checklist (Optional)

- [ ] Will pull request to branch of 2020.0.
- [ ] Will pull request to branch of 2022.0.

2023-09-21 02:52 UTC, SkyeBeFreeman requested changes
添加一下提交信息到CHANGELOG.md内~

2023-09-21 12:13 UTC, hligaty commented
CHANGELOG 已提交

2023-09-22 01:43 UTC, SkyeBeFreeman approved these changes

2023-09-22 01:44 UTC, SkyeBeFreeman commented
2022、2020、hoxton分支也cherry-pick一份

2023-09-22 02:02 UTC, merged