feat: add circuit breaker actuator
Tencent/spring-cloud-tencent pull request #1136
Opened 2023-09-22 11:57 UTC by wenxuan70

## PR Type

Feature

## Describe what this PR does for and how you did.
增加查询本服务相关的熔断规则

## Adding the issue link (#xxx) if possible.

fixes #1003

## Note

## Checklist

- [ ] Add information of this PR to CHANGELOG.md in root of project.
- [ ] Add documentation in javadoc or comment below the PR if necessary.

## Checklist (Optional)

- [ ] Will pull request to branch of 2020.0.
- [ ] Will pull request to branch of 2022.0.

2023-09-22 11:59 UTC, wenxuan70 commented
@SkyeBeFreeman 大佬有空帮忙review下代码

2023-09-22 15:39 UTC, SkyeBeFreeman requested changes

2023-09-22 15:39 UTC, SkyeBeFreeman commented on spring-cloud-tencent-polaris-context/src/main/java/com/tencent/cloud/polaris/context/ServiceRuleManager.java
> +		ServiceRule serviceRule = getServiceRule("", "", ServiceEventKey.EventType.CIRCUIT_BREAKING);
为啥没有传入命名空间和服务名？

2023-09-22 15:53 UTC, wenxuan70 commented on spring-cloud-tencent-polaris-context/src/main/java/com/tencent/cloud/polaris/context/ServiceRuleManager.java
> +		ServiceRule serviceRule = getServiceRule("", "", ServiceEventKey.EventType.CIRCUIT_BREAKING);
测试时候删掉了，加回来了

2023-09-25 02:16 UTC, SkyeBeFreeman approved these changes

2023-09-25 02:17 UTC, merged