feat: support lossless register and deregister
Tencent/spring-cloud-tencent pull request #1242
Opened 2024-03-11 03:53 UTC by shedfreewu

## PR Type

## Describe what this PR does for and how you did.
feat: support lossless register and deregister

## Note

## Checklist

- [ ] Add information of this PR to CHANGELOG.md in root of project.
- [ ] Add documentation in javadoc or comment below the PR if necessary.

2024-03-11 07:30 UTC, SkyeBeFreeman requested changes

2024-03-11 07:30 UTC, SkyeBeFreeman commented on spring-cloud-tencent-commons/src/main/java/com/tencent/cloud/common/util/ReflectionUtils.java
> +	 * 根据属性名返回对象的属性.
使用英文注释

2024-03-11 07:30 UTC, SkyeBeFreeman commented on spring-cloud-tencent-commons/src/main/java/com/tencent/cloud/common/util/ReflectionUtils.java
> +			throw new RuntimeException("getObjectByFieldName", e);
异常打印日志

2024-03-11 07:30 UTC, SkyeBeFreeman commented on spring-cloud-tencent-commons/src/main/java/com/tencent/cloud/common/util/ReflectionUtils.java
> +			throw new RuntimeException("getSuperObjectByFieldName", e);
异常打印日志

2024-03-11 07:30 UTC, SkyeBeFreeman commented on spring-cloud-tencent-commons/src/main/java/com/tencent/cloud/common/util/ReflectionUtils.java
> +			throw new RuntimeException("setValueByFieldName", e);
异常打印日志

2024-03-11 07:30 UTC, SkyeBeFreeman commented on spring-cloud-tencent-commons/src/main/java/com/tencent/cloud/common/util/ReflectionUtils.java
> +			throw new RuntimeException("setSuperValueByFieldName", e);
异常打印日志

2024-03-11 07:30 UTC, SkyeBeFreeman commented on spring-cloud-tencent-commons/src/main/java/com/tencent/cloud/common/util/ReflectionUtils.java
> +			throw new RuntimeException("setValue", e);
异常打印日志

2024-03-11 07:30 UTC, SkyeBeFreeman commented on spring-cloud-tencent-dependencies/pom.xml
> +			<dependency>
两个依赖，不在polaris-dependencies吗？

2024-03-11 07:30 UTC, SkyeBeFreeman commented on spring-cloud-tencent-plugin-starters/spring-cloud-tencent-lossless-plugin/pom.xml
> +			<artifactId>spring-cloud-tencent-polaris-context</artifactId>
dicovery应该包含了这个依赖

2024-03-11 07:30 UTC, SkyeBeFreeman commented on spring-cloud-tencent-plugin-starters/spring-cloud-tencent-lossless-plugin/pom.xml
> +			<artifactId>spring-cloud-tencent-commons</artifactId>
dicovery应该包含了这个依赖

2024-03-11 07:30 UTC, SkyeBeFreeman commented on spring-cloud-tencent-plugin-starters/spring-cloud-tencent-lossless-plugin/src/main/java/com/tencent/cloud/plugin/lossless/LosslessBeanPostProcessor.java
> +		// registration 通用，不设置 ns
使用英文注释

2024-03-11 07:30 UTC, SkyeBeFreeman commented on spring-cloud-tencent-plugin-starters/spring-cloud-tencent-lossless-plugin/src/main/java/com/tencent/cloud/plugin/lossless/LosslessProxyServiceRegistry.java
> +		// 需要兼容其他 discovery, spring cloud deregister 统一幂等处理
使用英文注释

2024-03-11 07:30 UTC, SkyeBeFreeman commented on spring-cloud-tencent-polaris-context/src/main/java/com/tencent/cloud/polaris/context/PolarisSDKContextManager.java
> +				// destroy ProviderAPI
api名称错误

2024-03-11 14:47 UTC, SkyeBeFreeman requested changes

2024-03-11 14:47 UTC, SkyeBeFreeman commented on spring-cloud-tencent-plugin-starters/spring-cloud-tencent-lossless-plugin/src/main/java/com/tencent/cloud/plugin/lossless/config/LosslessPropertiesBootstrapConfiguration.java
> +@Import(LosslessPropertiesAutoConfiguration.class)
需要判断polaris是否启动，可以参考其他BootstrapConfiguration。

2024-03-12 02:37 UTC, shedfreewu commented on spring-cloud-tencent-plugin-starters/spring-cloud-tencent-lossless-plugin/src/main/java/com/tencent/cloud/plugin/lossless/config/LosslessPropertiesBootstrapConfiguration.java
> +@Import(LosslessPropertiesAutoConfiguration.class)
这个插件预期是非 sct 也能用，不需要 polaris enabled

2024-03-12 04:04 UTC, SkyeBeFreeman approved these changes, later dismissed

2024-03-12 04:26 UTC, andrewshan approved these changes, later dismissed

2024-03-12 09:46 UTC, SkyeBeFreeman approved these changes

2024-03-12 09:46 UTC, merged