feat: add polaris router lane examples
Tencent/spring-cloud-tencent pull request #1260
Opened 2024-04-07 15:15 UTC by andrewshan

## PR Type

## Describe what this PR does for and how you did.

## Adding the issue link (#xxx) if possible.

## Note

## Checklist

- [ ] Add information of this PR to CHANGELOG.md in root of project.
- [ ] Add documentation in javadoc or comment below the PR if necessary.

## Checklist (Optional)

- [ ] Will pull request to branch of 2023.0.
- [ ] Will pull request to branch of 2022.0.
- [ ] Will pull request to branch of 2020.0.
- [ ] Will pull request to branch of hoxton.

2024-04-08 06:37 UTC, SkyeBeFreeman commented
要不然直接替换原本的`polaris-router-grayrelease-example`？

2024-04-08 11:40 UTC, SkyeBeFreeman commented on spring-cloud-tencent-examples/polaris-router-lane-example/route-lane-callee-service/src/main/resources/bootstrap.yml
> +server:
建议用application.yml

2024-04-08 11:41 UTC, SkyeBeFreeman reviewed
是否需要添加example的readme？

2024-04-12 11:44 UTC, andrewshan commented on spring-cloud-tencent-examples/polaris-router-lane-example/route-lane-callee-service/src/main/resources/bootstrap.yml
> +server:
已经修复

2024-04-12 11:45 UTC, andrewshan commented
> 要不然直接替换原本的`polaris-router-grayrelease-example`？

暂时先不替换，泳道只是实现灰度方案的一种方式，老的方案还是继续可以使用

2024-04-12 12:40 UTC, SkyeBeFreeman requested changes

2024-04-12 12:40 UTC, SkyeBeFreeman commented on spring-cloud-starter-tencent-polaris-router/src/main/resources/META-INF/additional-spring-configuration-metadata.json
> +      "description": "the match level for nearby router."
说明就近路由判定级别的几种选择

2024-04-12 12:54 UTC, SkyeBeFreeman approved these changes

2024-04-12 15:44 UTC, merged