feat: add spring cloud gateway mvc example
Tencent/spring-cloud-tencent pull request #1367
Opened 2024-08-07 07:33 UTC by fuyuwei01

## PR Type

Feature.

## Describe what this PR does for and how you did.
添加quickstart-gateway-mvc-example

## Adding the issue link (#xxx) if possible.

## Note

## Checklist

- [x] Add information of this PR to CHANGELOG.md in root of project.
- [ ] Add documentation in javadoc or comment below the PR if necessary.

## Checklist (Optional)

- [x] Will pull request to branch of 2023.
- [ ] Will pull request to branch of 2022.
- [ ] Will pull request to branch of 2021.
- [ ] Will pull request to branch of 2020.
- [ ] Will pull request to branch of hoxton.

2024-08-08 08:22 UTC, SkyeBeFreeman requested changes

2024-08-08 08:22 UTC, SkyeBeFreeman commented on spring-cloud-tencent-examples/quickstart-example/quickstart-gateway-mvc-service/pom.xml
> +	<name>Quickstart Gateway Service</name>
添加“MVC”

2024-08-08 08:22 UTC, SkyeBeFreeman commented on spring-cloud-tencent-examples/quickstart-example/quickstart-gateway-mvc-service/pom.xml
> +			<artifactId>spring-cloud-starter-tencent-all</artifactId>
用all包，服务调用不会有问题？因为默认引入了路由和熔断。

2024-08-08 08:22 UTC, SkyeBeFreeman commented on spring-cloud-tencent-examples/quickstart-example/quickstart-gateway-mvc-service/pom.xml
> +			<artifactId>spring-cloud-tencent-gateway-plugin</artifactId>
引入这个插件不会报错吗？

2024-08-08 08:22 UTC, SkyeBeFreeman commented on spring-cloud-tencent-examples/quickstart-example/quickstart-gateway-mvc-service/src/main/resources/application.yml
> +  port: 48080
使用48085

2024-08-08 08:48 UTC, fuyuwei01 commented on spring-cloud-tencent-examples/quickstart-example/quickstart-gateway-mvc-service/pom.xml
> +			<artifactId>spring-cloud-tencent-gateway-plugin</artifactId>
默认情况下这个插件不会启动，需要显式激活。显式激活后应用会因初始化TrafficStainingGatewayFilter报错。
更改为不引入该插件

2024-08-08 09:06 UTC, SkyeBeFreeman approved these changes, later dismissed

2024-08-08 09:30 UTC, SkyeBeFreeman approved these changes

2024-08-08 09:56 UTC, merged

2024-08-19 09:09 UTC, fuyuwei01 commented
在QuickstartGatewayMvcApplication复现https://github.com/Tencent/spring-cloud-tencent/issues/1351 

1. 配置与QuickstartGatewayApplication类似，application加入插件：
```yml
    tencent:
      plugin:
        scg:
          staining:
            enabled: true
            rule-staining:
              enabled: true
        router:
          feature-env:
            enabled: true
```
2. 引入scg插件依赖
```xml
		<dependency>
			<groupId>com.tencent.cloud</groupId>
			<artifactId>spring-cloud-tencent-gateway-plugin</artifactId>
		</dependency>
```