feat:add zero protection.
Tencent/spring-cloud-tencent pull request #1386
Opened 2024-08-14 11:16 UTC by fuyuwei01

## PR Type

## Describe what this PR does for and how you did.

## Adding the issue link (#xxx) if possible.

## Note

## Checklist

- [ ] Add information of this PR to CHANGELOG.md in root of project.
- [ ] Add documentation in javadoc or comment below the PR if necessary.

## Checklist (Optional)

- [ ] Will pull request to branch of 2023.
- [ ] Will pull request to branch of 2022.
- [ ] Will pull request to branch of 2021.
- [ ] Will pull request to branch of 2020.
- [ ] Will pull request to branch of hoxton.

2024-08-14 11:33 UTC, SkyeBeFreeman requested changes

2024-08-14 11:33 UTC, SkyeBeFreeman commented on spring-cloud-starter-tencent-polaris-discovery/src/main/resources/META-INF/additional-spring-configuration-metadata.json
> +      "name": "spring.cloud.polaris.discovery.zero-protection.enabled",
spring.cloud.polaris.loadbalancer配置需要保留

2024-08-14 11:34 UTC, SkyeBeFreeman approved these changes

2024-08-14 11:36 UTC, SkyeBeFreeman requested changes

2024-08-14 11:36 UTC, SkyeBeFreeman commented on spring-cloud-starter-tencent-polaris-contract/src/main/resources/META-INF/spring.factories
> +  com.tencent.cloud.polaris.contract.config.PolarisContractPropertiesBootstrapConfiguration
PolarisContractPropertiesAutoConfiguration的自动引入漏了

2024-08-15 03:41 UTC, fuyuwei01 commented
已验证2020版本使用bootstrap.yml或application.yml启动项目时，均能正常上报服务契约。
application.yml情况下
<img width="1699" alt="2020-contract-application" src="https://github.com/user-attachments/assets/9ce68f22-07f3-4e66-9fff-47ba6b2fd8b9">
bootstrap.yml情况下
<img width="1590" alt="2020-contract-bootstrap" src="https://github.com/user-attachments/assets/fc494711-88b1-4188-94d8-1a71a67af379">

2024-08-15 03:55 UTC, SkyeBeFreeman approved these changes

2024-08-15 03:55 UTC, merged