feat:add registerFilterHandler
Tencent/spring-cloud-tencent pull request #181
Opened 2022-05-18 11:48 UTC by imaxun

## PR Type

## Describe what this PR does for and how you did.

## Does this PR be associated with issue? If so, please adding the issue link below.

## Note

### Checklist
- [ ] Code compiles correctly
- [ ] Pull Request has submit to 2020.0 and Greenwich
- [ ] Create at least one junit test if possible
- [ ] All tests passing
- [ ] Extend documentation if necessary
- [ ] Add myself / the copyright holder to the AUTHORS file

2022-05-19 07:47 UTC, SkyeBeFreeman requested changes

2022-05-19 07:47 UTC, SkyeBeFreeman commented on spring-cloud-starter-tencent-polaris-discovery/src/main/java/com/tencent/cloud/polaris/registry/PolarisServiceRegistry.java
> +		this.addRegisterFilterHandler(new DefaultRegisterFilterHandler());
How can customized filter injected into registration?

2022-05-19 07:47 UTC, SkyeBeFreeman commented on spring-cloud-starter-tencent-polaris-discovery/src/main/java/com/tencent/cloud/polaris/registry/PolarisServiceRegistry.java
> +			registerFilterHandlerInstances.forEach(registerFilterHandler -> {
Why need to operate the registration request at the end?

2022-05-19 07:47 UTC, SkyeBeFreeman commented on spring-cloud-starter-tencent-polaris-discovery/src/main/java/com/tencent/cloud/polaris/registry/PolarisServiceRegistry.java
> +			registerFilterHandlerInstances.forEach(registerFilterHandler -> {
Why need to operate the registration request at the end?

2022-05-19 07:47 UTC, SkyeBeFreeman commented on spring-cloud-starter-tencent-polaris-discovery/src/main/java/com/tencent/cloud/polaris/registry/PolarisServiceRegistry.java
> -		catch (Exception e) {
Code style is not correct.

2022-05-19 07:47 UTC, SkyeBeFreeman commented on spring-cloud-starter-tencent-polaris-discovery/src/main/java/com/tencent/cloud/polaris/registry/PolarisServiceRegistry.java
> +		} catch (Exception e) {
Code style is not correct.

2022-05-19 07:47 UTC, SkyeBeFreeman commented on spring-cloud-starter-tencent-polaris-discovery/src/main/java/com/tencent/cloud/polaris/registry/PolarisServiceRegistry.java
> +		} catch (Exception e) {
Code style is not correct.

2022-05-19 07:47 UTC, SkyeBeFreeman commented on spring-cloud-starter-tencent-polaris-discovery/src/main/java/com/tencent/cloud/polaris/registry/PolarisServiceRegistry.java
> +		} finally {
Code style is not correct.

2022-05-19 07:47 UTC, SkyeBeFreeman commented on spring-cloud-starter-tencent-polaris-discovery/src/main/java/com/tencent/cloud/polaris/registry/PolarisServiceRegistry.java
> +		} finally {
Code style is not correct.

2022-05-19 07:47 UTC, SkyeBeFreeman commented on spring-cloud-starter-tencent-polaris-discovery/src/main/java/com/tencent/cloud/polaris/registry/PolarisServiceRegistry.java
> +				if (!registerFilterHandler.beforeInvoke(new RegisterFilterHandlerContext(instanceRegisterRequest))) {
Why not operating instanceRegisterRequest directly but operating RegisterFilterHandlerContext?

2022-05-19 07:47 UTC, SkyeBeFreeman commented on spring-cloud-starter-tencent-polaris-discovery/src/main/java/com/tencent/cloud/polaris/registry/PolarisServiceRegistry.java
> +				if (!registerFilterHandler.beforeInvoke(new RegisterFilterHandlerContext(instanceRegisterRequest))) {
Why not operating instanceRegisterRequest directly but operating RegisterFilterHandlerContext?

2022-05-19 07:47 UTC, SkyeBeFreeman commented on spring-cloud-starter-tencent-polaris-discovery/src/main/java/com/tencent/cloud/polaris/registry/PolarisServiceRegistry.java
> +			} catch (PolarisException e) {
Code style is not correct.

2022-05-19 07:47 UTC, SkyeBeFreeman commented on spring-cloud-starter-tencent-polaris-discovery/src/main/java/com/tencent/cloud/polaris/registry/PolarisServiceRegistry.java
> +			} catch (PolarisException e) {
Code style is not correct.

2022-05-19 07:47 UTC, SkyeBeFreeman commented on spring-cloud-starter-tencent-polaris-discovery/src/main/java/com/tencent/cloud/polaris/registry/PolarisServiceRegistry.java
> +			} catch (Exception e) {
Code style is not correct.

2022-05-19 07:47 UTC, SkyeBeFreeman commented on spring-cloud-starter-tencent-polaris-discovery/src/main/java/com/tencent/cloud/polaris/registry/PolarisServiceRegistry.java
> +			} catch (Exception e) {
Code style is not correct.

2022-05-19 07:47 UTC, SkyeBeFreeman commented on spring-cloud-starter-tencent-polaris-discovery/src/main/java/com/tencent/cloud/polaris/registry/PolarisServiceRegistry.java
> +	private List<RegisterFilterHandler> registerFilterHandlerInstances() {
Maybe bean injection is more useful.

2022-05-19 07:47 UTC, SkyeBeFreeman commented on spring-cloud-starter-tencent-polaris-discovery/src/main/java/com/tencent/cloud/polaris/registry/PolarisServiceRegistry.java
> +	private List<RegisterFilterHandler> registerFilterHandlerInstances() {
Maybe bean injection is more useful.

2022-05-19 07:47 UTC, SkyeBeFreeman commented on spring-cloud-starter-tencent-polaris-discovery/src/main/java/com/tencent/cloud/polaris/registry/PolarisServiceRegistryAutoConfiguration.java
> +		return Lists.newLinkedList();
What does this bean use for?

2022-05-19 07:47 UTC, SkyeBeFreeman commented on spring-cloud-starter-tencent-polaris-discovery/src/main/java/com/tencent/cloud/polaris/registry/PolarisServiceRegistryAutoConfiguration.java
> +		return Lists.newLinkedList();
What does this bean use for?

2022-05-19 07:47 UTC, SkyeBeFreeman commented on spring-cloud-starter-tencent-polaris-discovery/src/main/java/com/tencent/cloud/polaris/registry/filter/DefaultRegisterFilterHandler.java
> +		log.info("defaultRegisterFilterHandler beforeInvoke info");
Maybe change log level to debug, or just delete DefaultRegisterFilterHandler. I think this is just used for test for the time being.

2022-05-19 07:47 UTC, SkyeBeFreeman commented on spring-cloud-starter-tencent-polaris-discovery/src/main/java/com/tencent/cloud/polaris/registry/filter/DefaultRegisterFilterHandler.java
> +		log.info("defaultRegisterFilterHandler beforeInvoke info");
Maybe change log level to debug, or just delete DefaultRegisterFilterHandler. I think this is just used for test for the time being.

2022-05-19 07:47 UTC, SkyeBeFreeman commented on spring-cloud-starter-tencent-polaris-discovery/src/main/java/com/tencent/cloud/polaris/registry/filter/RegisterFilterHandler.java
> +	boolean beforeInvoke(RegisterFilterHandlerContext registerFilterHandlerContext);
Add comment for explaining what do these method do.

2022-05-19 07:47 UTC, SkyeBeFreeman commented on spring-cloud-starter-tencent-polaris-discovery/src/main/java/com/tencent/cloud/polaris/registry/filter/RegisterFilterHandler.java
> +	boolean beforeInvoke(RegisterFilterHandlerContext registerFilterHandlerContext);
Add comment for explaining what do these method do.

2022-05-19 07:47 UTC, SkyeBeFreeman commented on spring-cloud-starter-tencent-polaris-discovery/src/main/java/com/tencent/cloud/polaris/registry/filter/RegisterFilterHandlerContext.java
> +public class RegisterFilterHandlerContext {
Why use wrapper?

2022-05-19 07:47 UTC, SkyeBeFreeman commented on spring-cloud-starter-tencent-polaris-discovery/src/main/java/com/tencent/cloud/polaris/registry/filter/RegisterFilterHandlerContext.java
> +public class RegisterFilterHandlerContext {
Why use wrapper?

2022-05-19 16:53 UTC, imaxun commented on spring-cloud-starter-tencent-polaris-discovery/src/main/java/com/tencent/cloud/polaris/registry/filter/DefaultRegisterFilterHandler.java
> +		log.info("defaultRegisterFilterHandler beforeInvoke info");
可以调整日志为调试

2022-05-19 16:53 UTC, imaxun commented on spring-cloud-starter-tencent-polaris-discovery/src/main/java/com/tencent/cloud/polaris/registry/filter/RegisterFilterHandlerContext.java
> +public class RegisterFilterHandlerContext {
方便后续扩展

2022-05-19 16:54 UTC, imaxun commented on spring-cloud-starter-tencent-polaris-discovery/src/main/java/com/tencent/cloud/polaris/registry/PolarisServiceRegistry.java
> +			registerFilterHandlerInstances.forEach(registerFilterHandler -> {
一个是注册之前的处理一个是注册之后的

2022-05-19 16:59 UTC, imaxun commented on spring-cloud-starter-tencent-polaris-discovery/src/main/java/com/tencent/cloud/polaris/registry/PolarisServiceRegistry.java
> +		this.addRegisterFilterHandler(new DefaultRegisterFilterHandler());
可以通过spring @bean自动装配PolarisServiceRegistryAutoConfiguration中有加对应的实现demo

2022-05-19 17:01 UTC, imaxun commented on spring-cloud-starter-tencent-polaris-discovery/src/main/java/com/tencent/cloud/polaris/registry/filter/RegisterFilterHandlerContext.java
> +public class RegisterFilterHandlerContext {
为了后续如果有扩展都是用包装类传递

2022-05-19 17:02 UTC, imaxun commented on spring-cloud-starter-tencent-polaris-discovery/src/main/java/com/tencent/cloud/polaris/registry/PolarisServiceRegistry.java
> +		} catch (Exception e) {
不理解我用的自动格式化

2022-05-31 03:23 UTC, SkyeBeFreeman commented
@imaxun Plz fix the conflict.

2022-06-16 03:27 UTC, closed without merging