change the way from escape to encode in 2020.0
Tencent/spring-cloud-tencent pull request #257
Opened 2022-06-20 07:32 UTC by cheese8

PR Refactoring
Describe what this PR does for and how you did.
Ref https://github.com/Tencent/spring-cloud-tencent/issues/247

Does this PR be associated with issue? If so, please adding the issue link below.
change escape & unescape way into encode & decode way

2022-06-20 07:54 UTC, misselvexu commented
Please removed  unused imports , fix ci .

2022-06-20 09:58 UTC, misselvexu commented
Recommend combining multiple commits into a single commit .

2022-06-20 10:00 UTC, SkyeBeFreeman requested changes

2022-06-20 10:00 UTC, SkyeBeFreeman commented on spring-cloud-starter-tencent-polaris-router/src/test/java/com/tencent/cloud/polaris/router/feign/RouterLabelFeignInterceptorTest.java
> +				for (String value : routerLabelsMap.values()) {
this loop doesn't work.

2022-06-20 12:28 UTC, cheese8 commented
> @cheese8 Recommend combining multiple commits into a single commit .

OK

> @cheese8 Recommend combining multiple commits into a single commit .

that's a good idea.

2022-06-21 03:45 UTC, cheese8 commented on spring-cloud-starter-tencent-polaris-router/src/test/java/com/tencent/cloud/polaris/router/feign/RouterLabelFeignInterceptorTest.java
> +				for (String value : routerLabelsMap.values()) {
哈哈，确实是

2022-06-21 03:52 UTC, merged