feat: support actuator for sct core comments
Tencent/spring-cloud-tencent pull request #343
Opened 2022-06-29 05:08 UTC by shuiqingliu

This commit only support actuator of config, metadata, discovery and ratelimit.

## PR Type
Feature.

## Describe what this PR does for and how you did.
This PR has extend actuator of Spring Cloud Tencent. It only contains base info for core module.

## Adding the issue link (#xxx) if possible.
#243 

## Note

## Checklist

- [x] Add copyright holder at the beginning of .class file if it is new.
- [ ] Add information of this PR to CHANGELOG.md in root of project.
- [x] All junit tests passing.
- [x] Coverage from `Codecov Report` should not decrease.

## Checklist (Optional)

- [x] Will Pull Request to branch of 2020.0 and 2021.0.
- [x] Add documentation in javadoc in code or comment below the PR if necessary.
- [x] Add your name as @author to the beginning of .class file.

2022-06-29 05:38 UTC, misselvexu commented
@shuiqingliu  

Thank you for your first contribution PR ，Can provide a sample of the final output of all Actuator Endpoints ~

2022-06-29 06:16 UTC, shuiqingliu commented
@misselvexu I extract the final output from example module as follows.
PS: `ratelimit endpoint` has no fully test. I have not found a way to do that.

## 1. Service Discovery Endpoint
* url: ip:port/actuator/polaris-discovery

// http://127.0.0.1:48080/actuator/polaris-discovery/DiscoveryCalleeService
```json
{
  "PolarisDiscoveryProperties": {
    "namespace": "default",
    "service": "DiscoveryCallerService",
    "token": null,
    "weight": 100,
    "version": null,
    "protocol": "http",
    "port": 48080,
    "enabled": true,
    "registerEnabled": true,
    "heartbeatEnabled": true,
    "healthCheckUrl": "/discovery/service/caller/healthCheck",
    "serviceListRefreshInterval": 60000
  },
  "ServiceInstance": [
    {
      "scheme": "http",
      "uri": "http://10.97.61.101:48084",
      "secure": false,
      "instanceId": null,
      "metadata": {
        "k111111": "v1",
        "region": "application",
        "zone": "zone-z",
        "version": "",
        "protocol": "http",
        "boot": "true",
        "internal-address": "10.97.61.101:48084",
        "internal-ip": "10.97.61.101"
      },
      "serviceId": "DiscoveryCalleeService",
      "port": 48084,
      "host": "10.97.61.101"
    },
    {
      "scheme": "http",
      "uri": "http://192.168.1.72:48084",
      "secure": false,
      "instanceId": null,
      "metadata": {
        "internal-address": "192.168.1.72:48084",
        "internal-ip": "192.168.1.72",
        "k1": "v1",
        "zone": "shanghai",
        "version": "",
        "protocol": "http"
      },
      "serviceId": "DiscoveryCalleeService",
      "port": 48084,
      "host": "192.168.1.72"
    }
  ]
}
```
## 2. Polaris Ratelimit Endpoint

// http://127.0.0.1:48080/actuator/ratelimit/{namespace}/{serviceId}?dstService="test"

```json
{
  "rateLimits": [
    
  ],
  "service": "test",
  "namespace": "default",
  "properties": {
    "rejectRequestTips": null,
    "rejectRequestTipsFilePath": "reject-tips.html",
    "rejectHttpCode": 429,
    "maxQueuingTime": 500
  }
}
````

## 3. Polaris Config Endpoint

// http://127.0.0.1:48080/actuator/polaris-config
```json
{
  "PolarisPropertySource": [
    {
      "name": "default-polaris-config-example-config/application.properties",
      "source": {
        
      },
      "namespace": "default",
      "group": "polaris-config-example",
      "fileName": "config/application.properties",
      "propertySourceName": "default-polaris-config-example-config/application.properties",
      "propertyNames": [
        
      ]
    },
    {
      "name": "default-polaris-config-example-config/bootstrap.yml",
      "source": {
        
      },
      "namespace": "default",
      "group": "polaris-config-example",
      "fileName": "config/bootstrap.yml",
      "propertySourceName": "default-polaris-config-example-config/bootstrap.yml",
      "propertyNames": [
        
      ]
    },
    {
      "name": "default-polaris-config-example-bootstrap.properties",
      "source": {
        
      },
      "namespace": "default",
      "group": "polaris-config-example",
      "fileName": "bootstrap.properties",
      "propertySourceName": "default-polaris-config-example-bootstrap.properties",
      "propertyNames": [
        
      ]
    },
    {
      "name": "default-polaris-config-example-bootstrap.yml",
      "source": {
        
      },
      "namespace": "default",
      "group": "polaris-config-example",
      "fileName": "bootstrap.yml",
      "propertySourceName": "default-polaris-config-example-bootstrap.yml",
      "propertyNames": [
        
      ]
    },
    {
      "name": "default-polaris-config-example-application.yml",
      "source": {
        "teacher.age": "25",
        "teacher.name": "Skye"
      },
      "namespace": "default",
      "group": "polaris-config-example",
      "fileName": "application.yml",
      "propertySourceName": "default-polaris-config-example-application.yml",
      "propertyNames": [
        "teacher.age",
        "teacher.name"
      ]
    },
    {
      "name": "default-polaris-config-example-application.properties",
      "source": {
        "timeout": "888"
      },
      "namespace": "default",
      "group": "polaris-config-example",
      "fileName": "application.properties",
      "propertySourceName": "default-polaris-config-example-application.properties",
      "propertyNames": [
        "timeout"
      ]
    }
  ],
  "PolarisConfigProperties": {
    "enabled": true,
    "address": null,
    "port": 8093,
    "autoRefresh": true,
    "groups": [
      {
        "name": "polaris-config-example",
        "files": [
          "config/application.properties",
          "config/bootstrap.yml"
        ]
      }
    ]
  }
}
```

## 4. Metadata Endpoint
// http://127.0.0.1:48080/actuator/metadata

```json
{
  "zone": null,
  "Config": {
    "CUSTOM-METADATA-KEY-TRANSITIVE": "CUSTOM-VALUE-TRANSITIVE",
    "CUSTOM-METADATA-KEY-LOCAL": "CUSTOM-VALUE-LOCAL"
  },
  "campus": null,
  "ConfigTransitive": {
    "CUSTOM-METADATA-KEY-TRANSITIVE": "CUSTOM-VALUE-TRANSITIVE"
  },
  "MergeStatic": {
    "CUSTOM-METADATA-KEY-TRANSITIVE": "CUSTOM-VALUE-TRANSITIVE",
    "CUSTOM-METADATA-KEY-LOCAL": "CUSTOM-VALUE-LOCAL"
  },
  "Env": {
    
  },
  "region": null,
  "EnvTransitive": {
    
  }
}
```

2022-06-29 08:11 UTC, misselvexu commented
@shuiqingliu  Please resolve conflicts .

2022-06-29 11:22 UTC, shuiqingliu commented
@misselvexu done.

2022-06-30 02:26 UTC, SkyeBeFreeman requested changes

2022-06-30 02:26 UTC, SkyeBeFreeman commented on spring-cloud-starter-tencent-polaris-ratelimit/src/main/java/com/tencent/cloud/polaris/ratelimit/endpoint/PolarisRateLimitRuleEndpointAutoConfiguration.java
> +@ConditionalOnClass(Endpoint.class)
建议换成类名，否则当没有引入actuator依赖时找不到对应类。

2022-06-30 02:26 UTC, SkyeBeFreeman commented on spring-cloud-starter-tencent-polaris-ratelimit/src/test/java/com/tencent/cloud/polaris/ratelimit/endpoint/PolarisRateLimitRuleEndpointTests.java
> + *	Test for polaris rete limit rule endpoint.
删除多余的空格

2022-06-30 02:26 UTC, SkyeBeFreeman commented on spring-cloud-starter-tencent-polaris-ratelimit/src/test/java/com/tencent/cloud/polaris/ratelimit/endpoint/PolarisRateLimitRuleEndpointTests.java
> +	public void polarisRateLimit() {
改成`testPolarisRateLimit`

2022-06-30 02:26 UTC, SkyeBeFreeman commented on spring-cloud-starter-tencent-polaris-config/src/test/java/com/tencent/cloud/polaris/config/endpoint/PolarisConfigEndpointTests.java
> +	public void polarisConfigEndpoint() {
方法建议添加`test`前缀

2022-06-30 02:26 UTC, SkyeBeFreeman commented on spring-cloud-starter-tencent-polaris-discovery/src/test/java/com/tencent/cloud/polaris/endpoint/PolarisDiscoveryEndPointTests.java
> +	public void polarisDiscoveryEndpoint() {
方法建议添加`test`前缀

2022-06-30 02:26 UTC, SkyeBeFreeman commented on spring-cloud-tencent-commons/src/main/java/com/tencent/cloud/common/metadata/endpoint/MetadataEndpoint.java
> +		result.put("Env", staticMetadataManager.getAllEnvMetadata());
可以拉取新的代码，新的支持开发者使用接口的方式添加元数据——`customSPIMetadata`

2022-06-30 02:26 UTC, SkyeBeFreeman commented on spring-cloud-tencent-commons/src/main/java/com/tencent/cloud/common/metadata/endpoint/MetadataEndpointAutoConfiguration.java
> +@ConditionalOnClass(Endpoint.class)
建议替换为类名

2022-06-30 02:26 UTC, SkyeBeFreeman commented on spring-cloud-tencent-commons/src/test/java/com/tencent/cloud/common/metadata/endpoint/MetadataEndpointTests.java
> +	public void metadataEndpoint() {
建议添加`test`前缀

2022-06-30 02:26 UTC, SkyeBeFreeman commented on spring-cloud-starter-tencent-polaris-ratelimit/src/main/java/com/tencent/cloud/polaris/ratelimit/endpoint/PolarisRateLimitRuleEndpoint.java
> +@Endpoint(id = "ratelimit")
`polaris-ratelimit`是不是更好？区分出是北极星的限流

2022-06-30 02:26 UTC, SkyeBeFreeman commented on spring-cloud-tencent-examples/polaris-ratelimit-example/ratelimit-callee-service/src/main/resources/bootstrap.yml
> +          - ratelimit
`polaris-ratelimit`是不是更好？

2022-06-30 02:26 UTC, SkyeBeFreeman commented on spring-cloud-tencent-examples/metadata-transfer-example/metadata-caller-service/src/main/resources/bootstrap.yml
> +          - metadata
这里会不会引起歧义？因为spring cloud自带也有metadata

2022-06-30 07:03 UTC, misselvexu requested changes
@shuiqingliu 
1. Check the definition of all the Endpoint URL, unify the naming rules.
2. Check all requests JSON response value of the JSON-Key case specification unified, eg: hump, underscore, initial capitalization, etc.

2022-07-01 02:31 UTC, SkyeBeFreeman requested changes

2022-07-01 02:31 UTC, SkyeBeFreeman commented on spring-cloud-tencent-commons/src/main/java/com/tencent/cloud/common/metadata/endpoint/PolarisMetadataEndpointAutoConfiguration.java
> +@ConditionalOnClass(PolarisMetadataEndpoint.class)
改成`@ConditionalOnClass(Endpoint.class)`

2022-07-01 02:31 UTC, SkyeBeFreeman commented on spring-cloud-starter-tencent-polaris-config/src/main/java/com/tencent/cloud/polaris/config/endpoint/PolarisConfigEndpointAutoConfiguration.java
> +@ConditionalOnClass(PolarisConfigEndpoint.class)
改成`@ConditionalOnClass(Endpoint.class)`

2022-07-01 02:47 UTC, SkyeBeFreeman approved these changes
LGTM.

2022-07-01 09:59 UTC, merged

2022-07-01 10:23 UTC, misselvexu commented
@shuiqingliu  
Will you cherry-pick to branch 2020.0 and 2021.0 ？

2022-07-01 10:54 UTC, shuiqingliu commented
> 

yes. I will