optimize ：optimize test code format for check style
Tencent/spring-cloud-tencent pull request #374
Opened 2022-07-02 10:18 UTC by lingxiao-wu

## PR Type

Code style update (formatting, local variables).

## Describe what this PR does for and how you did.
optimize test code format to pass check style

## Adding the issue link (#xxx) if possible.

## Note

## Checklist

- [ ] Add copyright holder at the beginning of .class file if it is new.
- [ ] Add information of this PR to CHANGELOG.md in root of project.
- [ ] All junit tests passing.
- [ ] Coverage from `Codecov Report` should not decrease.

## Checklist (Optional)

- [ ] Will Pull Request to branch of 2020.0 and 2021.0.
- [ ] Add documentation in javadoc in code or comment below the PR if necessary.
- [ ] Add your name as @author to the beginning of .class file.

2022-07-02 10:28 UTC, SkyeBeFreeman commented
有些工作在 #368 已经做了～

2022-07-04 04:49 UTC, SkyeBeFreeman commented
@lingxiao-wu 重新拉一下main再看看

2022-07-04 12:45 UTC, misselvexu commented
@lingxiao-wu 
Please resolve conflicts .

2022-07-04 13:12 UTC, lingxiao-wu commented
> @lingxiao-wu 重新拉一下main再看看

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/51630311/177161823-19f7e5c3-bb8f-4ad9-afb5-867d07166259.png">
main分支还存在一些会阻塞maven test的style check

2022-07-04 13:24 UTC, SkyeBeFreeman requested changes

2022-07-04 13:24 UTC, SkyeBeFreeman commented on spring-cloud-starter-tencent-polaris-config/src/test/java/com/tencent/cloud/polaris/config/adapter/PolarisConfigFileLocatorTest.java
> + *@author lepdou 2022-06-11
这里不用修改

2022-07-04 13:24 UTC, SkyeBeFreeman commented on spring-cloud-starter-tencent-polaris-config/src/test/java/com/tencent/cloud/polaris/config/adapter/PolarisPropertiesSourceAutoRefresherTest.java
> + *@author lepdou 2022-06-11
这里不用修改

2022-07-04 13:24 UTC, SkyeBeFreeman commented on spring-cloud-starter-tencent-polaris-router/src/test/java/com/tencent/cloud/polaris/router/PolarisLoadBalancerCompositeRuleTest.java
> + *@author lepdou 2022-05-26
这里不用修改

2022-07-04 13:24 UTC, SkyeBeFreeman commented on spring-cloud-starter-tencent-polaris-router/src/test/java/com/tencent/cloud/polaris/router/RouterRuleLabelResolverTest.java
> + *@author lepdou 2022-05-26
这里不用修改

2022-07-04 13:24 UTC, SkyeBeFreeman commented on spring-cloud-starter-tencent-polaris-router/src/test/java/com/tencent/cloud/polaris/router/SimpleLoadBalancerTest.java
> + *@author lepdou 2022-05-26
这里不用修改

2022-07-04 13:24 UTC, SkyeBeFreeman commented on spring-cloud-starter-tencent-polaris-router/src/test/java/com/tencent/cloud/polaris/router/feign/FeignExpressionLabelUtilsTest.java
> + *@author lepdou 2022-05-26
这里不用修改

2022-07-04 13:24 UTC, SkyeBeFreeman commented on spring-cloud-starter-tencent-polaris-router/src/test/java/com/tencent/cloud/polaris/router/feign/PolarisCachingSpringLoadBalanceFactoryTest.java
> + *@author lepdou 2022-05-26
这里不用修改

2022-07-04 13:24 UTC, SkyeBeFreeman commented on spring-cloud-starter-tencent-polaris-router/src/test/java/com/tencent/cloud/polaris/router/feign/PolarisFeignLoadBalancerTest.java
> - *
这里不用修改

2022-07-04 13:24 UTC, SkyeBeFreeman commented on spring-cloud-starter-tencent-polaris-router/src/test/java/com/tencent/cloud/polaris/router/feign/RouterLabelFeignInterceptorTest.java
> + * @author lepdou 2022-05-26
这里不用修改

2022-07-04 13:24 UTC, SkyeBeFreeman commented on spring-cloud-starter-tencent-polaris-router/src/test/java/com/tencent/cloud/polaris/router/resttemplate/PolarisLoadBalancerBeanPostProcessorTest.java
> - *
这里不用修改

2022-07-04 13:24 UTC, SkyeBeFreeman commented on spring-cloud-starter-tencent-polaris-router/src/test/java/com/tencent/cloud/polaris/router/resttemplate/PolarisLoadBalancerInterceptorTest.java
> - *
这里不用修改

2022-07-04 13:24 UTC, SkyeBeFreeman commented on spring-cloud-starter-tencent-polaris-router/src/test/java/com/tencent/cloud/polaris/router/scg/PolarisLoadBalancerClientFilterTest.java
> + *@author lepdou 2022-06-13
这里不用修改

2022-07-04 13:24 UTC, SkyeBeFreeman commented on spring-cloud-tencent-commons/src/test/java/com/tencent/cloud/common/metadata/StaticMetadataManagerTest.java
>   *@author lepdou 2022-06-27
`@author`前面需要空格，且上方需要空行

2022-07-04 13:24 UTC, SkyeBeFreeman commented on spring-cloud-tencent-commons/src/test/java/com/tencent/cloud/common/util/AddressUtilsTest.java
> + *@author lepdou 2022-05-27
这里不用修改

2022-07-04 13:24 UTC, SkyeBeFreeman commented on spring-cloud-tencent-commons/src/test/java/com/tencent/cloud/common/util/ExpressionLabelUtilsTest.java
> + * @author lepdou 2022-05-27
这里不用修改

2022-07-04 13:24 UTC, SkyeBeFreeman commented on spring-cloud-tencent-commons/src/test/java/com/tencent/cloud/common/util/ResourceFileUtilsTest.java
> + *@author lepdou 2022-05-27
这里不用修改

2022-07-07 11:10 UTC, closed without merging