Optimize:optimize load balancer code and add testcase
Tencent/spring-cloud-tencent pull request #379
Opened 2022-07-03 11:39 UTC by lingxiao-wu

## PR Type

Code style update (formatting, local variables).

## Describe what this PR does for and how you did.

## Adding the issue link (#xxx) if possible.

## Note

## Checklist

- [ ] Add copyright holder at the beginning of .class file if it is new.
- [ ] Add information of this PR to CHANGELOG.md in root of project.
- [ ] All junit tests passing.
- [ ] Coverage from `Codecov Report` should not decrease.

## Checklist (Optional)

- [ ] Will Pull Request to branch of 2020.0 and 2021.0.
- [ ] Add documentation in javadoc in code or comment below the PR if necessary.
- [ ] Add your name as @author to the beginning of .class file.

2022-07-03 16:06 UTC, SkyeBeFreeman requested changes
Add info of this PR to CHANGELOG.md in the root of project.

2022-07-04 11:17 UTC, SkyeBeFreeman commented
@lingxiao-wu resolve the conflicts.

2022-07-04 13:00 UTC, lingxiao-wu commented on spring-cloud-tencent-polaris-loadbalancer/src/main/java/com/tencent/cloud/polaris/loadbalancer/LoadBalancerUtils.java
> +		List<Instance> instances = servers.toStream()
我已经改回去了

2022-07-04 13:14 UTC, SkyeBeFreeman approved these changes
LGTM.

2022-07-04 13:15 UTC, merged