add PostInitPolarisSDKContextTest
Tencent/spring-cloud-tencent pull request #404
Opened 2022-07-06 13:19 UTC by weihubeats

## add PostInitPolarisSDKContextTest

Feature.

## Describe what this PR does for and how you did.
add PostInitPolarisSDKContextTest

## Adding the issue link (#xxx) if possible.
https://github.com/Tencent/spring-cloud-tencent/issues/240

## Checklist

- [ ] Add copyright holder at the beginning of .class file if it is new.
- [ ] Add information of this PR to CHANGELOG.md in root of project.
- [ ] All junit tests passing.
- [ ] Coverage from `Codecov Report` should not decrease.

2022-07-06 13:20 UTC, weihubeats commented
I'm so sorry I accidentally deleted my fork repository

2022-07-06 14:05 UTC, SkyeBeFreeman requested changes
Add info of PR to CHANGELOG.md in the root of project.

2022-07-06 14:05 UTC, SkyeBeFreeman commented on spring-cloud-tencent-polaris-context/src/test/java/com/tencent/cloud/polaris/context/PostInitPolarisSDKContextTest.java
> +}
文件尾添加空行

2022-07-06 14:05 UTC, SkyeBeFreeman commented
> I'm so sorry I accidentally deleted my fork repository

Never mind😆

2022-07-06 15:42 UTC, weihubeats commented
done

2022-07-07 01:42 UTC, SkyeBeFreeman approved these changes
LGTM.

2022-07-07 01:42 UTC, merged