完善spring-cloud-starter-tencent-polaris-ratelimit的端点功能
Tencent/spring-cloud-tencent pull request #413
Opened 2022-07-07 13:46 UTC by weihubeats

## PR Type
<!--
Bugfix.

## Describe what this PR does for and how you did.
完善spring-cloud-starter-tencent-polaris-ratelimit的端点功能

## Adding the issue link (#xxx) if possible.
https://github.com/Tencent/spring-cloud-tencent/issues/411

## Note

## Checklist

- [ ] Add copyright holder at the beginning of .class file if it is new.
- [ ] Add information of this PR to CHANGELOG.md in root of project.
- [ ] All junit tests passing.
- [ ] Coverage from `Codecov Report` should not decrease.

2022-07-07 14:21 UTC, SkyeBeFreeman commented on CHANGELOG.md
> +- [UT: Add config module unit test](https://github.com/Tencent/spring-cloud-tencent/pull/229)
上个版本的已经移入changes目录下的1.6.0.md，这里只需要添加你自己的pr信息即可

2022-07-07 15:19 UTC, misselvexu requested changes

2022-07-07 15:27 UTC, misselvexu requested changes

2022-07-07 15:27 UTC, misselvexu commented on spring-cloud-tencent-commons/src/main/java/com/tencent/cloud/common/util/JacksonUtils.java
> +	public static Map<String, Object> json2Map(String jsonStr) {
Using the `deserialize2Map` method instead of `json2Map` method , without adding a method with duplicate functionality.

2022-07-08 02:05 UTC, SkyeBeFreeman requested changes

2022-07-08 02:05 UTC, SkyeBeFreeman commented on CHANGELOG.md
> +- [Feature: Add config change listener feature support](https://github.com/Tencent/spring-cloud-tencent/pull/220)
Info of 1.6.0 PRs should not be added.

2022-07-08 02:24 UTC, weihubeats commented on CHANGELOG.md
> +- [Feature: Add config change listener feature support](https://github.com/Tencent/spring-cloud-tencent/pull/220)
I'll be consistent with main here

2022-07-08 02:27 UTC, SkyeBeFreeman commented
Don't remove your PR info in the CHANGELOG.md.

2022-07-08 02:29 UTC, weihubeats commented
> Don't remove your PR info in the CHANGELOG.md.

Now the CHANGELOG.md above the main point is empty. .

2022-07-08 02:31 UTC, weihubeats commented
I will delete 229 and 220 in the CHANGELOG.md I just submitted, right?

2022-07-08 02:32 UTC, SkyeBeFreeman commented
> > Don't remove your PR info in the CHANGELOG.md.
> 
> Now the CHANGELOG.md above the main point is empty. .

Because your PR is the first PR in version of 1.7.0😂Just add your PR info in the CHANGELOG.md.

<img width="372" alt="image" src="https://user-images.githubusercontent.com/24446200/177905095-07eb0b66-53cf-4546-877a-ba0115d6c4a4.png">

2022-07-08 02:34 UTC, weihubeats commented
I see

2022-07-08 02:43 UTC, misselvexu approved these changes

2022-07-08 02:49 UTC, SkyeBeFreeman approved these changes

2022-07-08 03:05 UTC, merged

2022-07-08 03:06 UTC, SkyeBeFreeman commented
You can cherry-pick to branch of 2020 and 2021.

2022-07-08 03:08 UTC, weihubeats commented
ok