Feature：support MetadataContext transfer in thread pool
Tencent/spring-cloud-tencent pull request #422
Opened 2022-07-09 12:45 UTC by lingxiao-wu

## PR Type

Feature

## Describe what this PR does for and how you did.
support MetadataContext transfer in thread pool

## Adding the issue link (#xxx) if possible.
#372

## Note
wrap ExecutorService like this to transfer MetadataContext in thread pool
```java 
ExecutorService metadataExecutorService =
				MetadataExecutors.getMetadataExecutorService(Executors.newFixedThreadPool(1));

ScheduledExecutorService metadataScheduledExecutorService =
				MetadataExecutors.getMetadataScheduledExecutorService(Executors.newSingleThreadScheduledExecutor());

```

## Checklist

- [ ] Add copyright holder at the beginning of .class file if it is new.
- [ ] Add information of this PR to CHANGELOG.md in root of project.
- [ ] All junit tests passing.
- [ ] Coverage from `Codecov Report` should not decrease.

## Checklist (Optional)

- [ ] Will Pull Request to branch of 2020.0 and 2021.0.
- [ ] Add documentation in javadoc in code or comment below the PR if necessary.
- [ ] Add your name as @author to the beginning of .class file.

2022-07-10 03:43 UTC, misselvexu requested changes
@lingxiao-wu 

**Very important**：

1、After a preliminary look at the code, the core code basically comes from the `transmittable-thread-local` project, so why not just use an independent third-party dependency library? This does not comply with the Apache2 open source license.

2022-07-10 03:43 UTC, misselvexu commented on spring-cloud-starter-tencent-metadata-transfer/src/main/java/com/tencent/cloud/metadata/concurrent/MetadataCallable.java
> +
Remove duplicate blank lines

2022-07-10 03:43 UTC, misselvexu commented on spring-cloud-starter-tencent-metadata-transfer/src/main/java/com/tencent/cloud/metadata/concurrent/MetadataCallable.java
> +}
Add a blank line to the last line

2022-07-10 03:43 UTC, misselvexu commented on spring-cloud-starter-tencent-metadata-transfer/src/main/java/com/tencent/cloud/metadata/concurrent/MetadataRunnable.java
> +}
Add a blank line to the last line

2022-07-10 03:43 UTC, misselvexu commented on spring-cloud-starter-tencent-metadata-transfer/src/main/java/com/tencent/cloud/metadata/concurrent/MetadataWrap.java
> +}
Add a blank line to the last line

2022-07-10 03:43 UTC, misselvexu commented on spring-cloud-starter-tencent-metadata-transfer/src/main/java/com/tencent/cloud/metadata/concurrent/executor/MetadataExecutor.java
> +}
Add a blank line to the last line

2022-07-10 03:43 UTC, misselvexu commented on spring-cloud-starter-tencent-metadata-transfer/src/main/java/com/tencent/cloud/metadata/concurrent/executor/MetadataExecutorService.java
> +}
Add a blank line to the last line

2022-07-10 03:43 UTC, misselvexu commented on spring-cloud-starter-tencent-metadata-transfer/src/main/java/com/tencent/cloud/metadata/concurrent/executor/MetadataExecutors.java
> +}
Add a blank line to the last line

2022-07-10 03:43 UTC, misselvexu commented on spring-cloud-starter-tencent-metadata-transfer/src/main/java/com/tencent/cloud/metadata/concurrent/executor/MetadataExecutors.java
> +
Remove blank line

2022-07-10 03:43 UTC, misselvexu commented on spring-cloud-starter-tencent-metadata-transfer/src/main/java/com/tencent/cloud/metadata/concurrent/executor/MetadataExecutors.java
> +
Remove blank line

2022-07-10 03:43 UTC, misselvexu commented on spring-cloud-starter-tencent-metadata-transfer/src/main/java/com/tencent/cloud/metadata/concurrent/executor/MetadataScheduledExecutorService.java
> +}
Add a blank line to the last line

2022-07-10 03:43 UTC, misselvexu commented on spring-cloud-starter-tencent-metadata-transfer/src/test/java/com/tencent/cloud/metadata/concurrent/MetadataCallableTest.java
> +}
Add a blank line to the last line

2022-07-10 03:43 UTC, misselvexu commented on spring-cloud-starter-tencent-metadata-transfer/src/test/java/com/tencent/cloud/metadata/concurrent/MetadataRunnableTest.java
> +}
Add a blank line to the last line

2022-07-10 05:14 UTC, lingxiao-wu commented
> @lingxiao-wu
> 
> **Very important**：
> 
> 1、After a preliminary look at the code, the core code basically comes from the `transmittable-thread-local` project, so why not just use an independent third-party dependency library? This does not comply with the Apache2 open source license.

支持这个功能本质上是提供一系列java线程池相关的包装类，在设计包装类的时候有一些方法确实借鉴了`transmittable-thread-local`的优秀设计，如果担心许可问题，可以添加`transmittable-thread-local`依赖，SPT的包装类做中间桥梁，将java 线程池包装成`transmittable-thread-local`线程池使用，支持元数据在线程池正确获取

2022-07-10 05:24 UTC, lingxiao-wu commented
> > @lingxiao-wu
> > **Very important**：
> > 1、After a preliminary look at the code, the core code basically comes from the `transmittable-thread-local` project, so why not just use an independent third-party dependency library? This does not comply with the Apache2 open source license.
> 
> 支持这个功能本质上是提供一系列java线程池相关的包装类，在设计包装类的时候有一些方法确实借鉴了`transmittable-thread-local`的优秀设计，如果担心许可问题，可以添加`transmittable-thread-local`依赖，SPT的包装类做中间桥梁，将java 线程池包装成`transmittable-thread-local`线程池使用，支持元数据在线程池正确获取


其实借鉴的地方并不多，只是Runnable和Callable的包装类通过工厂方法获取这个地方借鉴了一下，其他类MetadataExecutor用于增强Executor，MetadataExecutorService用于增强ExecutorService，MetadataScheduledExecutorService用于增强ScheduledExecutorService，MetadataExecutors参考jdk的Executors，提供快速创建包装后线程池的工厂方法。

2022-07-10 05:26 UTC, lingxiao-wu commented
> > @lingxiao-wu
> > **Very important**：
> > 1、After a preliminary look at the code, the core code basically comes from the `transmittable-thread-local` project, so why not just use an independent third-party dependency library? This does not comply with the Apache2 open source license.
> 
> 支持这个功能本质上是提供一系列java线程池相关的包装类，在设计包装类的时候有一些方法确实借鉴了`transmittable-thread-local`的优秀设计，如果担心许可问题，可以添加`transmittable-thread-local`依赖，SPT的包装类做中间桥梁，将java 线程池包装成`transmittable-thread-local`线程池使用，支持元数据在线程池正确获取


其实借鉴的地方并不多，只是Runnable和Callable的包装类通过工厂方法获取这个地方借鉴了一下，其他类MetadataExecutor用于增强Executor，MetadataExecutorService用于增强ExecutorService，MetadataScheduledExecutorService用于增强ScheduledExecutorService，MetadataExecutors参考jdk的Executors，提供快速创建包装后线程池的工厂方法。

2022-07-11 07:47 UTC, SkyeBeFreeman requested changes
在根目录的LICENSE文件，添加`transmittable-thread-local`的版权声明。

<img width="560" alt="image" src="https://user-images.githubusercontent.com/24446200/178214284-700b1524-94a0-483d-a183-e782adc9e221.png">

2022-07-12 05:56 UTC, misselvexu requested changes
At this moment , `MetadataContextHolder#METADATA_CONTEXT` field , should we use `TransmittableThreadLocal ` instead of `InheritableThreadLocal` ?

2022-07-12 05:56 UTC, misselvexu commented on spring-cloud-starter-tencent-metadata-transfer/src/test/java/com/tencent/cloud/metadata/concurrent/executor/MetadataExecutorTest.java
> +			Assertions.assertThat(fragmentContextBeforeInit.equals(fragmentContext));
`Assertions.assertThat()` missing `isTrue()` method ?

2022-07-12 05:56 UTC, misselvexu commented on spring-cloud-starter-tencent-metadata-transfer/src/test/java/com/tencent/cloud/metadata/concurrent/executor/MetadataExecutorTest.java
> +			Assertions.assertThat(fragmentContextAfterInit.equals(fragmentContext));
Assertions.assertThat() missing isTrue() method ?

2022-07-12 05:56 UTC, misselvexu commented on spring-cloud-starter-tencent-metadata-transfer/src/main/java/com/tencent/cloud/metadata/concurrent/executor/MetadataExecutors.java
> +
Remove blank line.

2022-07-12 05:56 UTC, misselvexu commented on spring-cloud-starter-tencent-metadata-transfer/src/main/java/com/tencent/cloud/metadata/concurrent/MetadataWrap.java
> +public interface MetadataWrap<T> {
Is it possible to use `TtlWrapper` directly if `transmittable-thread-local` is already integrated ?

2022-07-12 05:56 UTC, misselvexu commented on spring-cloud-starter-tencent-metadata-transfer/src/main/java/com/tencent/cloud/metadata/concurrent/executor/MetadataExecutor.java
> +
Remove blank line.

2022-07-12 05:56 UTC, misselvexu commented on spring-cloud-starter-tencent-metadata-transfer/pom.xml
> +
Remove blank line.

2022-07-12 05:56 UTC, misselvexu commented on spring-cloud-starter-tencent-metadata-transfer/src/main/java/com/tencent/cloud/metadata/concurrent/executor/MetadataExecutorService.java
> +
Remove blank line.

2022-07-12 05:56 UTC, misselvexu commented on spring-cloud-starter-tencent-metadata-transfer/src/main/java/com/tencent/cloud/metadata/concurrent/executor/MetadataScheduledExecutorService.java
> +
Remove blank line.

2022-07-12 05:56 UTC, misselvexu commented on spring-cloud-starter-tencent-metadata-transfer/src/test/java/com/tencent/cloud/metadata/concurrent/MetadataTestUtil.java
> +
Remove blank line.

2022-07-12 05:56 UTC, misselvexu commented on spring-cloud-starter-tencent-metadata-transfer/src/test/java/com/tencent/cloud/metadata/concurrent/executor/MetadataExecutorServiceTest.java
> +
Remove blank line.

2022-07-12 05:56 UTC, misselvexu commented on spring-cloud-starter-tencent-metadata-transfer/src/test/java/com/tencent/cloud/metadata/concurrent/executor/MetadataExecutorTest.java
> +
Remove blank line.

2022-07-12 05:56 UTC, misselvexu commented on spring-cloud-starter-tencent-metadata-transfer/src/test/java/com/tencent/cloud/metadata/concurrent/executor/MetadataExecutorsTest.java
> +
Remove blank line.

2022-07-12 05:56 UTC, misselvexu commented on spring-cloud-starter-tencent-metadata-transfer/src/test/java/com/tencent/cloud/metadata/concurrent/executor/MetadataScheduledExecutorServiceTest.java
> +
Remove blank line.

2022-07-12 05:56 UTC, misselvexu commented on spring-cloud-tencent-dependencies/pom.xml
> +
Remove blank line.

2022-07-22 05:36 UTC, misselvexu commented
@lingxiao-wu 

Thank you for your PR submission on #372 this issue, but sorry, we revisited the application scenario of cross-requirement pool passing and the implementation of cross-thread pool data passing, and in the end we felt not to introduce the `transmittable-thread-local` dependency library, and we do not provide an API for cross-thread pool implementation at the SCT level.

The specific reasons are as follows.
1, `transmittable-thread-local` is an excellent three-way framework library and provides a variety of implementations, such as: agent-based implementations, modified thread pools, modified Runnable and Callable, etc.
2, in the current PR, the implementation of the `MetadataExecutor ` wrap support, but its application scenarios and use of `transmittable-thread-local ` similar, we do not feel the need to have multiple implementations of the same feature-function, for the user to use the choice to cause trouble and confusion.
3. We will provide detailed descriptions and suggested implementation methods and demos for this scenario in our Wiki documentation.

Finally, sorry again for closing the current PR.

We hope you will continue to pay attention to SCT and participate in our discussions and weekly meetings.

2022-07-22 05:49 UTC, closed without merging