Optimize: add EncodeTransferMedataRestTemplateInterceptor to RestTemp…
Tencent/spring-cloud-tencent pull request #439
Opened 2022-07-15 12:57 UTC by DerekYRC

## PR Type

Refactoring

## Describe what this PR does for and how you did.

Optimize: add EncodeTransferMedataRestTemplateInterceptor to RestTemplate.

优化代码：为RestTemplate添加拦截器EncodeTransferMedataRestTemplateInterceptor。

## Adding the issue link (#xxx) if possible.

https://github.com/Tencent/spring-cloud-tencent/issues/431

## Note

参照LoadBalancerAutoConfiguration中为RestTemplate添加LoadBalancerInterceptor拦截器的做法，在配置类中注入所有RestTemplate，然后为其添加EncodeTransferMedataRestTemplateInterceptor拦截器

## Checklist

- [x] Add copyright holder at the beginning of .class file if it is new.
- [x] Add information of this PR to CHANGELOG.md in root of project.
- [x] All junit tests passing.
- [x] Coverage from `Codecov Report` should not decrease.

## Checklist (Optional)

- [x] Will Pull Request to branch of 2020.0 and 2021.0.
- [x] Add documentation in javadoc in code or comment below the PR if necessary.
- [x] Add your name as @author to the beginning of .class file.

2022-07-15 23:34 UTC, SkyeBeFreeman requested changes

2022-07-15 23:34 UTC, SkyeBeFreeman commented on CHANGELOG.md
> +- [Optimize: add EncodeTransferMedataRestTemplateInterceptor to RestTemplate](https://github.com/Tencent/spring-cloud-tencent/pull/434)
修改为正确的PR号

2022-07-16 01:10 UTC, DerekYRC commented on CHANGELOG.md
> +- [Optimize: add EncodeTransferMedataRestTemplateInterceptor to RestTemplate](https://github.com/Tencent/spring-cloud-tencent/pull/434)
修改了

2022-07-16 02:00 UTC, SkyeBeFreeman approved these changes

2022-07-16 02:01 UTC, merged