add router actuator endpoint
Tencent/spring-cloud-tencent pull request #464
Opened 2022-07-25 10:44 UTC by lepdou

## PR Type

## Describe what this PR does for and how you did.

## Adding the issue link (#xxx) if possible.

## Note

## Checklist

- [ ] Add copyright holder at the beginning of .class file if it is new.
- [ ] Add information of this PR to CHANGELOG.md in root of project.
- [ ] All junit tests passing.
- [ ] Coverage from `Codecov Report` should not decrease.

## Checklist (Optional)

- [ ] Will Pull Request to branch of 2020.0 and 2021.0.
- [ ] Add documentation in javadoc in code or comment below the PR if necessary.
- [ ] Add your name as @author to the beginning of .class file.

2022-07-25 12:06 UTC, SkyeBeFreeman submitted a review, later dismissed
LGTM.

2022-07-25 12:19 UTC, misselvexu submitted a review, later dismissed

2022-07-25 15:22 UTC, misselvexu requested changes

2022-07-25 15:22 UTC, misselvexu commented on spring-cloud-starter-tencent-polaris-discovery/src/test/java/com/tencent/cloud/polaris/endpoint/PolarisDiscoveryEndpointTest.java
> +			PolarisDiscoveryEndpoint polarisDiscoveryEndPoint = new PolarisDiscoveryEndpoint(polarisDiscoveryProperties, discoveryClient, polarisDiscoveryHandler);
Rename `polarisDiscoveryEndPoint` to `polarisDiscoveryEndpoint` .

2022-07-26 03:33 UTC, misselvexu approved these changes

2022-07-26 03:34 UTC, merged