feature:add @ConditionalOnConfigReflectEnabled annotation
Tencent/spring-cloud-tencent pull request #496
Opened 2022-08-06 01:56 UTC by lingxiao-wu

## PR Type
Feature

## Describe what this PR does for and how you did.
add @ConditionalOnConfigReflectEnabled annotation

## Adding the issue link (#xxx) if possible.
#470 

## Note

## Checklist

- [ ] Add copyright holder at the beginning of .class file if it is new.
- [ ] Add information of this PR to CHANGELOG.md in root of project.
- [ ] All junit tests passing.
- [ ] Coverage from `Codecov Report` should not decrease.

## Checklist (Optional)

- [ ] Will Pull Request to branch of 2020.0 and 2021.0.
- [ ] Add documentation in javadoc in code or comment below the PR if necessary.
- [ ] Add your name as @author to the beginning of .class file.

2022-08-09 08:28 UTC, misselvexu requested changes

2022-08-09 08:28 UTC, misselvexu commented on spring-cloud-starter-tencent-polaris-config/src/main/java/com/tencent/cloud/polaris/config/adapter/PolarisPropertySourceRefresher.java
> +public interface PolarisPropertySourceRefresher {
Wouldn't it be better to name this class `PolarisConfigPropertyRefresher`?
Defining it as `PolarisPropertySourceRefresher` seems to be a bit misunderstood ~

2022-08-09 08:28 UTC, misselvexu commented on spring-cloud-starter-tencent-polaris-config/src/test/java/com/tencent/cloud/polaris/config/condition/ConditionalOnConfigReflectEnabledTest.java
> +	public void testReflectEnable() {
Rename `testReflectEnable` to `testReflectEnabled` ?

2022-08-09 08:28 UTC, misselvexu commented on spring-cloud-starter-tencent-polaris-config/src/test/java/com/tencent/cloud/polaris/config/condition/ConditionalOnConfigReflectEnabledTest.java
> +import org.junit.jupiter.api.Test;
Using `import org.junit.Test;`  instead of `import org.junit.jupiter.api.Test;` .

2022-08-09 08:28 UTC, misselvexu commented on spring-cloud-starter-tencent-polaris-config/src/test/java/com/tencent/cloud/polaris/config/condition/ConditionalOnConfigReflectEnabledTest.java
> +	public void testWithoutReflectEnable() {
Rename `testWithoutReflectEnable` to `testWithoutReflectEnabled` ?

2022-08-09 15:58 UTC, misselvexu submitted a review, later dismissed

2022-08-09 15:58 UTC, misselvexu commented
LGTM.

2022-08-11 11:37 UTC, misselvexu approved these changes

2022-08-11 11:37 UTC, merged

2022-08-24 07:05 UTC, SkyeBeFreeman commented
@lingxiao-wu 方便也提交到2020和2021分支吗？

2022-08-24 07:12 UTC, lingxiao-wu commented
> @lingxiao-wu 方便也提交到2020和2021分支吗？

最近在酒店隔离没带电脑，你先合并一下吧嘿嘿🤤🤤🤤

2022-08-24 07:16 UTC, SkyeBeFreeman commented
> > @lingxiao-wu 方便也提交到2020和2021分支吗？
> 
> 最近在酒店隔离没带电脑，你先合并一下吧嘿嘿🤤🤤🤤

好，我晚点直接cherry-pick一下