Feature：support pushGateway push metrics
Tencent/spring-cloud-tencent pull request #504
Opened 2022-08-13 03:30 UTC by lingxiao-wu

## PR Type
Feature

## Describe what this PR does for and how you did.
支持以pushGateway方式上传监控数据
可以通过如下方式配置开启
```yml
spring:
  cloud:
    polaris:
      stat:
        enabled: true
        port: 28081
        pushgateway:
          enabled: true # 开启pushgateway上传
          address: 192.168.31.119:9091 # pushgateway地址
          grouping-keys: # pushgateway grouping-keys
            instance: DiscoveryCallerService1
          push-rate: 1m # pushgateway push频率
          shut-down-strategy: delete # 应用关闭时pushgateway上报策略,为了避免实例已经下线prometheus依然拉取数据，可以设置delete，清除pushgateway上该实例的数据
          job: DiscoveryCallerService # pushgateway 任务名称，默认去spring.application.name
```

## Adding the issue link (#xxx) if possible.
#471 
## Note

## Checklist

- [ ] Add copyright holder at the beginning of .class file if it is new.
- [ ] Add information of this PR to CHANGELOG.md in root of project.
- [ ] All junit tests passing.
- [ ] Coverage from `Codecov Report` should not decrease.

## Checklist (Optional)

- [ ] Will Pull Request to branch of 2020.0 and 2021.0.
- [ ] Add documentation in javadoc in code or comment below the PR if necessary.
- [ ] Add your name as @author to the beginning of .class file.

2022-08-16 02:43 UTC, SkyeBeFreeman requested changes
这里有一个比较重要的点，就是需要使用北极星SDK的`stat-pushgateway`插件来帮助实现，然后pushgateway的相关代码作为独立插件实现在`spring-cloud-tencent/tree/main/spring-cloud-tencent-plugin-starters`这个目录下。开发之前需要大致写一下设计思路，然后大家一起评审一下更好~

2022-08-17 07:28 UTC, SkyeBeFreeman commented
是否需要给拉取模式也添加一个开关，用于判断只开启pushgateway方式？

2022-08-18 13:04 UTC, lingxiao-wu commented
> 是否需要给拉取模式也添加一个开关，用于判断只开启pushgateway方式？

目前我考虑的配置方式大概如下
同时开启两种方式将两个开关打开即可
```yaml
spring:
  cloud:
    polaris:
      stat:
        enabled: true
        pushgateway:
          enabled: true
```
只开启pushgatewat可以只开启pushgateway开关
```yaml
spring:
  cloud:
    polaris:
      stat:
        pushgateway:
          enabled: true
```
只开启prometheus 上报，开启stat开关即可
spring:
  cloud:
    polaris:
      stat:
          enabled: true
```
感觉可能已经覆盖了一些常用的组合方式，不需要在添加一个开关，用于判断只开启pushgateway方式

2022-08-19 13:02 UTC, lingxiao-wu commented
> 是否需要给拉取模式也添加一个开关，用于判断只开启pushgateway方式？

我查看`stat-pushgateway`插件实现的时候发现可以通过pushgatewayService和pushgatewayNamespace来获取 pushgateway地址，这种场景下我本地应该怎么验证，或者pushgatewayService和pushgatewayNamespace我应该配置什么参数
<img width="1335" alt="image" src="https://user-images.githubusercontent.com/51630311/185623817-3a95fdaa-78b9-4cd2-8165-22a9e5efeae4.png">

2022-08-22 10:12 UTC, SkyeBeFreeman commented
> > 是否需要给拉取模式也添加一个开关，用于判断只开启pushgateway方式？
> 
> 我查看`stat-pushgateway`插件实现的时候发现可以通过pushgatewayService和pushgatewayNamespace来获取 pushgateway地址，这种场景下我本地应该怎么验证，或者pushgatewayService和pushgatewayNamespace我应该配置什么参数 <img alt="image" width="1335" src="https://user-images.githubusercontent.com/51630311/185623817-3a95fdaa-78b9-4cd2-8165-22a9e5efeae4.png">

目前先做ip地址上报的方式吧，如果准备就绪了，我这边就review，然后合并代码

2022-08-22 10:22 UTC, SkyeBeFreeman commented on spring-cloud-tencent-dependencies/pom.xml
> +			<dependency>
在discovery的example展示pushgateway的使用

2022-08-22 10:35 UTC, SkyeBeFreeman commented on spring-cloud-tencent-rpc-enhancement/src/main/java/com/tencent/cloud/rpc/enhancement/condition/PushGatewayCondition.java
> +		Environment environment = context.getEnvironment();
`POLARIS_STAT_ENABLED` 为 false ，`POLARIS_STAT_PUSH_GATEWAY_ENABLED ` 为 true 的时候，不能使用pushgateway？

2022-08-22 13:34 UTC, lingxiao-wu commented on spring-cloud-tencent-rpc-enhancement/src/main/java/com/tencent/cloud/rpc/enhancement/condition/PushGatewayCondition.java
> +		Environment environment = context.getEnvironment();
这个代码我删除了，这是之前我没有借助polaris的时候写的

2022-08-23 03:45 UTC, SkyeBeFreeman approved these changes

2022-08-23 03:45 UTC, merged