bugfix issues/593
Tencent/spring-cloud-tencent pull request #594
Opened 2022-09-14 15:46 UTC by 77321660

bugfix issues https://github.com/Tencent/spring-cloud-tencent/issues/593

2022-09-15 09:41 UTC, SkyeBeFreeman requested changes
在根目录下的CHANGELOG.md添加PR信息

2022-09-15 09:55 UTC, SkyeBeFreeman commented
Add junit test for `RouterLabelRestTemplateInterceptor `.

2022-09-16 02:06 UTC, SkyeBeFreeman requested changes

2022-09-16 02:06 UTC, SkyeBeFreeman commented on spring-cloud-starter-tencent-polaris-router/src/test/java/com/tencent/cloud/polaris/router/resttemplate/RouterLabelRestTemplateInterceptorTest.java
> +		Assert.assertEquals("v1", headers.get("k1"));
使用 `Assertions.assertThat()` 方法

2022-09-16 09:26 UTC, lepdou approved these changes

2022-09-16 09:38 UTC, merged