Automatically transmit some headers specified by a environment varaible that directly defines header keys.
Tencent/spring-cloud-tencent pull request #606
Opened 2022-09-23 15:46 UTC by pandaapo

## PR Type
Feature.

## Describe what this PR does for and how you did.
Automatically transmit some headers specified by a environment varaible that directly defines header keys.
Use the `MetadataContext` to build headers needed to be transmitted. When current service sends request, attach the transitive headers saved in `MetadataContext` before.

## Adding the issue link (#xxx) if possible.
#563

## Note
Junit tests will be made up later.

## Checklist

- [ ] Add copyright holder at the beginning of .class file if it is new.
- [x] Add information of this PR to CHANGELOG.md in root of project.
- [ ] All junit tests passing.
- [ ] Coverage from `Codecov Report` should not decrease.

## Checklist (Optional)

- [x] Will Pull Request to branch of hoxton.
- [x] Add documentation in javadoc in code or comment below the PR if necessary.

2022-09-24 08:18 UTC, andrewshan commented
测试用例不通过，麻烦确认下

2022-09-24 09:03 UTC, leopardrota commented
好。没来得及写，还是旧的测试代码。

2022-09-24 10:58 UTC, chuntaojun requested changes

2022-09-24 10:58 UTC, chuntaojun commented on spring-cloud-starter-tencent-metadata-transfer/src/main/java/com/tencent/cloud/metadata/core/DecodeTransferMetadataReactiveFilter.java
> +			String[] transHeaderArray = transHeaders.get().split(";");
Optional.get() 会抛 Null 异常，使用 orElse 避免异常吧

2022-09-24 10:58 UTC, chuntaojun commented on spring-cloud-starter-tencent-metadata-transfer/src/main/java/com/tencent/cloud/metadata/core/DecodeTransferMetadataServletFilter.java
> +			String[] transHeaderArray = transHeaders.get().split(";");
同上

2022-09-24 10:58 UTC, chuntaojun commented on spring-cloud-starter-tencent-metadata-transfer/src/main/java/com/tencent/cloud/metadata/core/DecodeTransferMetadataServletFilter.java
> +			String[] transHeaderArray = transHeaders.get().split(";");
下面的方法抽象到 transfer 吧

2022-09-25 00:03 UTC, pandaapo commented
> 测试用例不通过，麻烦确认下

好。没来得及写，还是之前的测试代码。

2022-09-26 04:15 UTC, chuntaojun requested changes

2022-09-26 04:15 UTC, chuntaojun commented on spring-cloud-tencent-commons/src/main/java/com/tencent/cloud/common/metadata/StaticMetadataManager.java
> +	private static final String ENV_METADATA_CONTENT_RAW_TRANSHEADERS = "SCT_METADATA_CONTENT_RAW_TRANSHEADERS";
这里新增的这个信息，会注册到北极星的实例中去，这个可能需要处理下，这个是不需要注册到实例的元数据中的

2022-09-26 10:51 UTC, andrewshan commented
> 的

会导致之前的测试代码跑不过吗？

2022-09-26 11:02 UTC, merged

2022-09-27 21:49 UTC, pandaapo commented on spring-cloud-starter-tencent-metadata-transfer/src/main/java/com/tencent/cloud/metadata/core/DecodeTransferMetadataReactiveFilter.java
> +			String[] transHeaderArray = transHeaders.get().split(";");
OK

2022-09-27 21:50 UTC, pandaapo commented on spring-cloud-starter-tencent-metadata-transfer/src/main/java/com/tencent/cloud/metadata/core/DecodeTransferMetadataServletFilter.java
> +			String[] transHeaderArray = transHeaders.get().split(";");
OK

2022-09-27 21:52 UTC, pandaapo commented on spring-cloud-starter-tencent-metadata-transfer/src/main/java/com/tencent/cloud/metadata/core/DecodeTransferMetadataServletFilter.java
> +			String[] transHeaderArray = transHeaders.get().split(";");
不太确定您的意思，是要将这段在多个类之间重复的代码提取成工具类公用代码吗？

2022-09-27 21:53 UTC, pandaapo commented on spring-cloud-tencent-commons/src/main/java/com/tencent/cloud/common/metadata/StaticMetadataManager.java
> +	private static final String ENV_METADATA_CONTENT_RAW_TRANSHEADERS = "SCT_METADATA_CONTENT_RAW_TRANSHEADERS";
不好意思，没来及处理。感谢帮助处理了。