Maybe remove Chinese characters
Tencent/spring-cloud-tencent pull request #607
Opened 2022-09-24 10:10 UTC by galaxy-sea

## PR Type
Code style update (formatting, local variables).

## Describe what this PR does for and how you did.

## Adding the issue link (#xxx) if possible.

## Note

## Checklist

- [ ] Add copyright holder at the beginning of .class file if it is new.
- [ ] Add information of this PR to CHANGELOG.md in root of project.
- [ ] All junit tests passing.
- [ ] Coverage from `Codecov Report` should not decrease.

## Checklist (Optional)

- [ ] Will Pull Request to branch of 2020.0 and hoxton.
- [ ] Add documentation in javadoc in code or comment below the PR if necessary.

2022-09-24 10:41 UTC, SkyeBeFreeman requested changes

2022-09-24 10:41 UTC, SkyeBeFreeman commented on spring-cloud-starter-tencent-polaris-ratelimit/src/test/java/com/tencent/cloud/polaris/ratelimit/filter/QuotaCheckReactiveFilterTest.java
> +		polarisRateLimitProperties.setRejectRequestTips("RejectRequestTips prompt message");
这里是为了测试中文字符输出，无需修改

2022-09-24 10:41 UTC, SkyeBeFreeman commented on spring-cloud-starter-tencent-polaris-ratelimit/src/test/java/com/tencent/cloud/polaris/ratelimit/filter/QuotaCheckReactiveFilterTest.java
> +			assertThat(rejectTips.get(quotaCheckReactiveFilter)).isEqualTo("RejectRequestTips prompt message");
这里是为了测试中文字符输出，无需修改

2022-09-24 10:41 UTC, SkyeBeFreeman commented on spring-cloud-starter-tencent-polaris-ratelimit/src/test/java/com/tencent/cloud/polaris/ratelimit/filter/QuotaCheckServletFilterTest.java
> +		polarisRateLimitProperties.setRejectRequestTips("RejectRequestTips prompt message");
这里是为了测试中文字符输出，无需修改

2022-09-24 10:41 UTC, SkyeBeFreeman commented on spring-cloud-starter-tencent-polaris-ratelimit/src/test/java/com/tencent/cloud/polaris/ratelimit/filter/QuotaCheckServletFilterTest.java
> +			assertThat(rejectTips.get(quotaCheckServletFilter)).isEqualTo("RejectRequestTips prompt message");
这里是为了测试中文字符输出，无需修改

2022-09-24 10:41 UTC, SkyeBeFreeman commented on spring-cloud-starter-tencent-polaris-ratelimit/src/test/java/com/tencent/cloud/polaris/ratelimit/filter/QuotaCheckServletFilterTest.java
> +			assertThat(rejectTips.get(quotaCheckWithHtmlRejectTipsServletFilter)).isEqualTo("<h1>RejectRequestTips prompt message</h1>");
这里是为了测试中文字符输出，无需修改

2022-09-24 10:41 UTC, SkyeBeFreeman commented on spring-cloud-starter-tencent-polaris-ratelimit/src/test/java/com/tencent/cloud/polaris/ratelimit/filter/QuotaCheckServletFilterTest.java
> +			assertThat(response.getContentAsString()).isEqualTo("RejectRequestTips prompt message");
这里是为了测试中文字符输出，无需修改

2022-09-24 10:41 UTC, SkyeBeFreeman commented on spring-cloud-starter-tencent-polaris-ratelimit/src/test/java/com/tencent/cloud/polaris/ratelimit/filter/QuotaCheckServletFilterTest.java
> +			assertThat(response.getContentAsString()).isEqualTo("RejectRequestTips prompt message");
这里是为了测试中文字符输出，无需修改

2022-09-24 11:01 UTC, SkyeBeFreeman approved these changes
请问是否会cherry-pick到其他分支呢？

2022-09-25 01:01 UTC, SkyeBeFreeman requested changes
在CHANGELOG.md中添加PR信息

2022-09-25 02:29 UTC, galaxy-sea commented
> 在CHANGELOG.md中添加PR信息

Added

2022-09-25 03:14 UTC, SkyeBeFreeman approved these changes

2022-09-25 03:15 UTC, merged