[ISSUE #563] fix pr #606 cause ci fail
Tencent/spring-cloud-tencent pull request #613
Opened 2022-09-26 14:45 UTC by chuntaojun

## PR Type

## Describe what this PR does for and how you did.

## Adding the issue link (#xxx) if possible.

## Note

## Checklist

- [ ] Add copyright holder at the beginning of .class file if it is new.
- [ ] Add information of this PR to CHANGELOG.md in root of project.
- [ ] All junit tests passing.
- [ ] Coverage from `Codecov Report` should not decrease.

## Checklist (Optional)

- [ ] Will Pull Request to branch of 2020.0 and hoxton.
- [ ] Add documentation in javadoc in code or comment below the PR if necessary.

2022-09-26 14:52 UTC, SkyeBeFreeman requested changes

2022-09-26 14:52 UTC, SkyeBeFreeman commented on CHANGELOG.md
> -- [Optimize: Maybe remove Chinese characters](https://github.com/Tencent/spring-cloud-tencent/pull/607)
添加你的pr信息，不要删除其他开发者的pr信息～

2022-09-27 03:12 UTC, SkyeBeFreeman approved these changes

2022-09-27 03:13 UTC, merged

2022-09-27 21:32 UTC, pandaapo commented
不好意思，没及时处理。感谢。

2022-09-27 22:31 UTC, pandaapo reviewed
做了如下一点补充

2022-09-27 22:45 UTC, pandaapo commented on spring-cloud-tencent-commons/src/main/java/com/tencent/cloud/common/metadata/StaticMetadataManager.java
>  					&& !key.equals(ENV_METADATA_CONTENT_TRANSITIVE)) {
`ENV_METADATA_CONTENT_RAW_TRANSHEADERS`改成`ENV_TRAFFIC_CONTENT_RAW_TRANSHEADERS`后，这个判断要做点补充，不然会把`ENV_TRAFFIC_CONTENT_RAW_TRANSHEADERS`排除掉。

已在PR #618 中处理。