Optimize:optimize transfer
Tencent/spring-cloud-tencent pull request #636
Opened 2022-10-11 08:05 UTC by lingxiao-wu

## PR Type
Optimize

## Describe what this PR does for and how you did.
优化元数据传递相关代码，主要修改点
1.DecodeTransferMetadataServletFilter添加finally块清除MetadataContextHolder
2.抽取TransHeadersTransfer工具类，封装TransHeaders从请求头保存到MetadataContext逻辑
3.在MetadataContext中增加getXXX(),setXXX()方法，将不同元数据的获取逻辑封装在MetadataContext中，减少外部对于不同类型元数据key的感知

## Adding the issue link (#xxx) if possible.

## Note

## Checklist

- [ ] Add copyright holder at the beginning of .class file if it is new.
- [ ] Add information of this PR to CHANGELOG.md in root of project.
- [ ] All junit tests passing.
- [ ] Coverage from `Codecov Report` should not decrease.

## Checklist (Optional)

- [ ] Will Pull Request to branch of 2020.0 and hoxton.
- [ ] Add documentation in javadoc in code or comment below the PR if necessary.

2022-10-11 11:46 UTC, SkyeBeFreeman requested changes
补充一下PR信息到CHANGELOG.md

2022-10-12 03:25 UTC, SkyeBeFreeman commented on spring-cloud-starter-tencent-metadata-transfer/src/main/java/com/tencent/cloud/metadata/core/DecodeTransferMetadataServletFilter.java
> +			filterChain.doFilter(httpServletRequest, httpServletResponse);
这里出现异常的话，是不是应该再抛出来？

2022-10-12 10:02 UTC, lingxiao-wu commented on spring-cloud-starter-tencent-metadata-transfer/src/main/java/com/tencent/cloud/metadata/core/DecodeTransferMetadataServletFilter.java
> +			filterChain.doFilter(httpServletRequest, httpServletResponse);
这块如果异常的话会正常抛出的，因为代码没有catch块，不会把异常吞掉

2022-10-13 08:18 UTC, SkyeBeFreeman approved these changes

2022-10-13 08:18 UTC, merged

2022-10-14 12:04 UTC, SkyeBeFreeman commented
@lingxiao-wu 看下是否有空将这个pr cherry-pick到2020分支呢？

2022-10-14 12:38 UTC, lingxiao-wu commented
> @lingxiao-wu 看下是否有空将这个pr cherry-pick到2020分支呢？

ok

2022-10-25 02:33 UTC, SkyeBeFreeman commented
@lingxiao-wu 可以提交到Hoxton分支不？