revert default value when the field is deleted in @ConfigurationPrope…
Tencent/spring-cloud-tencent pull request #699
Opened 2022-11-04 12:21 UTC by dongyinuo

…rties bean. (#681)

## PR Type
enhancement

## Describe what this PR does for and how you did.
revert default value when the field is deleted in @ConfigurationProperties bean

## Adding the issue link (#xxx) if possible.
https://github.com/Tencent/spring-cloud-tencent/issues/681

## Note

## Checklist

- [ ] Coverage from `Codecov Report` should not decrease (which means adding junit tests for adding or updating code).
- [ ] All junit tests passing.
- [ ] Add copyright holder at the beginning of .java file if it is new.
- [ ] Add information of this PR to CHANGELOG.md in root of project.

## Checklist (Optional)

- [ ] Will Pull Request to branch of 2020.0 and hoxton.
- [ ] Add documentation in javadoc or comment below the PR if necessary.

2022-11-05 01:00 UTC, SkyeBeFreeman commented
@dongyinuo 请参考这个配置，设置好开发环境，以通过代码风格检查，[代码规范](https://github.com/Tencent/spring-cloud-tencent/wiki/%E5%8F%82%E4%B8%8E%E5%85%B1%E5%BB%BA#%E4%BB%A3%E7%A0%81%E8%A7%84%E8%8C%83)。

2022-11-06 00:16 UTC, dongyinuo commented
> @dongyinuo 请参考这个配置，设置好开发环境，以通过代码风格检查，[代码规范](https://github.com/Tencent/spring-cloud-tencent/wiki/%E5%8F%82%E4%B8%8E%E5%85%B1%E5%BB%BA#%E4%BB%A3%E7%A0%81%E8%A7%84%E8%8C%83)。

好的

2022-11-07 01:28 UTC, dongyinuo commented
> > @dongyinuo 请参考这个配置，设置好开发环境，以通过代码风格检查，[代码规范](https://github.com/Tencent/spring-cloud-tencent/wiki/%E5%8F%82%E4%B8%8E%E5%85%B1%E5%BB%BA#%E4%BB%A3%E7%A0%81%E8%A7%84%E8%8C%83)。
> 
> 好的

2022-11-07 01:30 UTC, dongyinuo commented
> > > @dongyinuo 请参考这个配置，设置好开发环境，以通过代码风格检查，[代码规范](https://github.com/Tencent/spring-cloud-tencent/wiki/%E5%8F%82%E4%B8%8E%E5%85%B1%E5%BB%BA#%E4%BB%A3%E7%A0%81%E8%A7%84%E8%8C%83)。
> > 
> > 
> > 好的

@SkyeBeFreeman 已按照代码规范，格式代码，编译通过

2022-11-07 01:51 UTC, SkyeBeFreeman commented
> > > > @dongyinuo 请参考这个配置，设置好开发环境，以通过代码风格检查，[代码规范](https://github.com/Tencent/spring-cloud-tencent/wiki/%E5%8F%82%E4%B8%8E%E5%85%B1%E5%BB%BA#%E4%BB%A3%E7%A0%81%E8%A7%84%E8%8C%83)。
> > > 
> > > 
> > > 好的
> 
> @SkyeBeFreeman 已按照代码规范，格式代码，编译通过

好的，我重启一下GitHub Action

2022-11-08 03:56 UTC, lepdou requested changes

2022-11-08 03:56 UTC, lepdou commented on spring-cloud-starter-tencent-polaris-config/src/main/java/com/tencent/cloud/polaris/config/adapter/AffectedConfigurationPropertiesRebinder.java
> +				ReflectionUtils.doWithFields(instance.getClass(), field -> {
我测试了一下，Spring Boot ConfigurationProperties 的bean 只有有 setter 方法的属性才会注入。这里是不是可以优化一下，也只存有 setter 方法的属性的默认值呢？

主要担心，有的业务代码可能在 ConfigurationProperties 里存一些解析之后的对象之类的？

你觉得呢

2022-11-08 03:58 UTC, lepdou commented on spring-cloud-starter-tencent-polaris-config/src/main/java/com/tencent/cloud/polaris/config/adapter/AffectedConfigurationPropertiesRebinder.java
> +				ReflectionUtils.doWithFields(instance.getClass(), field -> {
我记得Spring 好像有工具类，判断属性是否有setter方法

2022-11-08 04:29 UTC, dongyinuo commented on spring-cloud-starter-tencent-polaris-config/src/main/java/com/tencent/cloud/polaris/config/adapter/AffectedConfigurationPropertiesRebinder.java
> +				ReflectionUtils.doWithFields(instance.getClass(), field -> {
嗯嗯，好的，我下午 试一下

2022-11-08 08:29 UTC, dongyinuo commented on spring-cloud-starter-tencent-polaris-config/src/main/java/com/tencent/cloud/polaris/config/adapter/AffectedConfigurationPropertiesRebinder.java
> +				ReflectionUtils.doWithFields(instance.getClass(), field -> {
> 我记得Spring 好像有工具类，判断属性是否有setter方法

@lepdou 参考 Introspector & PropertyDescriptor 判断 set 方法的，改了一下，您在 review 一下

2022-11-08 08:31 UTC, lepdou commented on spring-cloud-starter-tencent-polaris-config/src/main/java/com/tencent/cloud/polaris/config/adapter/AffectedConfigurationPropertiesRebinder.java
> +					String setMethodName = SET_PREFIX + capitalize(field.getName());
这里应该不能简单的通过 set前缀判断，如果是 boolean 类型，是is开头的。我找一下spring 里的工具类

2022-11-08 08:51 UTC, dongyinuo commented on spring-cloud-starter-tencent-polaris-config/src/main/java/com/tencent/cloud/polaris/config/adapter/AffectedConfigurationPropertiesRebinder.java
> +					String setMethodName = SET_PREFIX + capitalize(field.getName());
嗯嗯，好的，辛苦了，帮忙找一下，或者我在 sct-commons 里加一个方法 判断 field 字段是否 可写(set、或者 is 前缀)？

2022-11-08 09:06 UTC, lepdou commented on spring-cloud-starter-tencent-polaris-config/src/main/java/com/tencent/cloud/polaris/config/adapter/AffectedConfigurationPropertiesRebinder.java
> +					String setMethodName = SET_PREFIX + capitalize(field.getName());
找了半天，没找到(⊙o⊙)…

要不就自己写个util 方法，再判断一下 field 的类型如果是 Boolean，isXx 就可以了？

2022-11-08 09:09 UTC, dongyinuo commented on spring-cloud-starter-tencent-polaris-config/src/main/java/com/tencent/cloud/polaris/config/adapter/AffectedConfigurationPropertiesRebinder.java
> +					String setMethodName = SET_PREFIX + capitalize(field.getName());
嗯嗯，好的，我写一个

2022-11-10 00:59 UTC, dongyinuo commented on spring-cloud-starter-tencent-polaris-config/src/main/java/com/tencent/cloud/polaris/config/adapter/AffectedConfigurationPropertiesRebinder.java
> +					String setMethodName = SET_PREFIX + capitalize(field.getName());
@lepdou 我大概测试了一下，针对 boolean 的字段， @configurationproperties 只会 对 有 set 方法的注入，比如 setIsXXX, 所以 我们是不是 恢复默认值时，只针对 set 方法即可

<img width="1388" alt="image" src="https://user-images.githubusercontent.com/45160106/200974430-9ded0335-5888-4aaa-a735-51c6c45b70a9.png">

2022-11-11 08:05 UTC, lepdou approved these changes

2022-11-11 08:12 UTC, lepdou approved these changes

2022-11-11 08:12 UTC, merged

2022-11-13 10:19 UTC, SkyeBeFreeman commented
@dongyinuo 看下能否提交到2020和Hoxton分支？

2022-11-13 10:19 UTC, SkyeBeFreeman commented
@dongyinuo 看下能否提交到2020和Hoxton分支？