add test 2sct polaris router
Tencent/spring-cloud-tencent pull request #731
Opened 2022-11-16 02:05 UTC by dongyinuo

## PR Type
add sct-stater-polaris-router juint

<img width="620" alt="image" src="https://user-images.githubusercontent.com/45160106/202065782-0a1b3ddd-4252-429e-b970-a3df083e379b.png">

## Describe what this PR does for and how you did.
add sct-stater-polaris-router juint

## Adding the issue link (#xxx) if possible.
https://github.com/Tencent/spring-cloud-tencent/issues/682

## Note

## Checklist

- [ ] Coverage from `Codecov Report` should not decrease (which means adding junit tests for adding or updating code).
- [ ] All junit tests passing.
- [ ] Add copyright holder at the beginning of .java file if it is new.
- [ ] Add information of this PR to CHANGELOG.md in root of project.

## Checklist (Optional)

- [ ] Will Pull Request to branch of 2020.0 and hoxton.
- [ ] Add documentation in javadoc or comment below the PR if necessary.

2022-11-16 02:18 UTC, SkyeBeFreeman requested changes

2022-11-16 02:18 UTC, SkyeBeFreeman commented on spring-cloud-starter-tencent-polaris-router/src/test/java/com/tencent/cloud/polaris/router/config/properties/PolarisMetadataRouterPropertiesTest.java
> +		System.out.println(properties);
可以改为设置值，然后将tostring的调用结果进行对比。

2022-11-16 02:18 UTC, SkyeBeFreeman commented on spring-cloud-starter-tencent-polaris-router/src/test/java/com/tencent/cloud/polaris/router/config/properties/PolarisNearByRouterPropertiesTest.java
> +		System.out.println(properties);
可以改为设置值，然后将tostring的调用结果进行对比。

2022-11-16 02:18 UTC, SkyeBeFreeman commented on spring-cloud-starter-tencent-polaris-router/src/test/java/com/tencent/cloud/polaris/router/config/properties/PolarisRuleBasedRouterPropertiesTest.java
> +		System.out.println(properties);
可以改为设置值，然后将tostring的调用结果进行对比。

2022-11-16 02:18 UTC, SkyeBeFreeman commented on spring-cloud-starter-tencent-polaris-router/src/test/java/com/tencent/cloud/polaris/router/resttemplate/PolarisLoadBalancerRequestTests.java
> +			System.out.println("Mock LoadBalancerRequest");
不使用system.out输出，可以利用verify方法来判断调用次数

2022-11-16 02:25 UTC, dongyinuo commented on spring-cloud-starter-tencent-polaris-router/src/test/java/com/tencent/cloud/polaris/router/resttemplate/PolarisLoadBalancerRequestTests.java
> +			System.out.println("Mock LoadBalancerRequest");
好的， 我统一该一版

2022-11-24 14:00 UTC, dongyinuo commented
已统一修复

2022-11-25 02:04 UTC, SkyeBeFreeman commented
@dongyinuo 查看一下单测问题

2022-11-29 07:47 UTC, tencent-adm commented
[![CLA assistant check](https://cla.opensource.tencent.com/pull/badge/not_signed)](https://cla.opensource.tencent.com/Tencent/spring-cloud-tencent?pullRequest=731) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.opensource.tencent.com/Tencent/spring-cloud-tencent?pullRequest=731) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: SkyeBeFreeman<br/>:x: dongyinuo<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.tencent.com/check/Tencent/spring-cloud-tencent?pullRequest=731) it.</sub>

2022-11-29 08:38 UTC, SkyeBeFreeman requested changes
@dongyinuo 修复单测错误

2022-12-07 08:23 UTC, SkyeBeFreeman submitted a review, later dismissed

2022-12-07 08:57 UTC, SkyeBeFreeman approved these changes

2022-12-07 09:04 UTC, merged