fix:nacos & polaris discovery
Tencent/spring-cloud-tencent pull request #816
Opened 2023-01-28 08:20 UTC by chuntaojun

## PR Type

## Describe what this PR does for and how you did.

## Adding the issue link (#xxx) if possible.

## Note

## Checklist

- [ ] Coverage from `Codecov Report` should not decrease (which means adding junit tests for adding or updating code).
- [ ] All junit tests passing.
- [ ] Add copyright holder at the beginning of .java file if it is new.
- [ ] Add information of this PR to CHANGELOG.md in root of project.

## Checklist (Optional)

- [ ] Will Pull Request to branch of 2020.0 and hoxton.
- [ ] Add documentation in javadoc or comment below the PR if necessary.

2023-01-28 08:20 UTC, tencent-adm commented
[![CLA assistant check](https://cla.opensource.tencent.com/pull/badge/not_signed)](https://cla.opensource.tencent.com/Tencent/spring-cloud-tencent?pullRequest=816) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.tencent.com/Tencent/spring-cloud-tencent?pullRequest=816) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.tencent.com/check/Tencent/spring-cloud-tencent?pullRequest=816) it.</sub>

2023-01-29 04:50 UTC, SkyeBeFreeman requested changes
Plz add PR info to CHANGELOG.md.

2023-01-29 07:37 UTC, SkyeBeFreeman commented on spring-cloud-tencent-commons/src/main/java/com/tencent/cloud/common/util/DiscoveryUtil.java
> +		String enableNacos = ApplicationContextAwareUtils.getProperties("spring.cloud.nacos.enabled");
这些字段是不是可以不用每次都从context获取？第一次获取的时候就存起来？

2023-01-29 07:39 UTC, chuntaojun commented on spring-cloud-tencent-commons/src/main/java/com/tencent/cloud/common/util/DiscoveryUtil.java
> +		String enableNacos = ApplicationContextAwareUtils.getProperties("spring.cloud.nacos.enabled");
ok

2023-01-30 07:59 UTC, SkyeBeFreeman requested changes
更新到最新版本polaris-java

2023-01-31 01:30 UTC, SkyeBeFreeman approved these changes

2023-01-31 01:30 UTC, merged