feature:add PolarisRateLimiterLimitedFallback spi.
Tencent/spring-cloud-tencent pull request #830
Opened 2023-02-12 06:47 UTC by lingxiao-wu

## PR Type
Feature

## Describe what this PR does for and how you did.
feature:add PolarisRateLimiterLimitedFallback spi.

## Adding the issue link (#xxx) if possible.
#800 

## Note

## Checklist

- [ ] Coverage from `Codecov Report` should not decrease (which means adding junit tests for adding or updating code).
- [ ] All junit tests passing.
- [ ] Add copyright holder at the beginning of .java file if it is new.
- [ ] Add information of this PR to CHANGELOG.md in root of project.

## Checklist (Optional)

- [ ] Will Pull Request to branch of 2020.0 and hoxton.
- [ ] Add documentation in javadoc or comment below the PR if necessary.

2023-02-12 06:47 UTC, tencent-adm commented
[![CLA assistant check](https://cla.opensource.tencent.com/pull/badge/not_signed)](https://cla.opensource.tencent.com/Tencent/spring-cloud-tencent?pullRequest=830) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.tencent.com/Tencent/spring-cloud-tencent?pullRequest=830) before we can accept your contribution.<br/><hr/>**Lingxiao.Wu** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.tencent.com/check/Tencent/spring-cloud-tencent?pullRequest=830) it.</sub>

2023-02-13 06:24 UTC, misselvexu requested changes

2023-02-13 06:24 UTC, misselvexu commented on spring-cloud-starter-tencent-polaris-ratelimit/src/main/java/com/tencent/cloud/polaris/ratelimit/spi/PolarisRateLimiterLimitedFallback.java
> + * Date: 2023-02-08 22:59:27
Remove the illegal javadoc annotation.

2023-02-13 06:24 UTC, misselvexu commented on spring-cloud-starter-tencent-polaris-ratelimit/src/main/java/com/tencent/cloud/polaris/ratelimit/spi/PolarisRateLimiterLimitedFallback.java
> +	 * @return Customized rejectHttpCode
incorrect meaning of the return value .

2023-02-13 06:24 UTC, misselvexu commented on spring-cloud-starter-tencent-polaris-ratelimit/src/test/java/com/tencent/cloud/polaris/ratelimit/filter/JsonPolarisRateLimiterLimitedFallback.java
> + * Date: 2023-02-11 22:57:25
Removed `Date` annotation .

2023-02-16 02:17 UTC, lepdou commented on spring-cloud-starter-tencent-polaris-ratelimit/src/test/java/com/tencent/cloud/polaris/ratelimit/filter/JsonPolarisRateLimiterLimitedFallback.java
> +public class JsonPolarisRateLimiterLimitedFallback implements PolarisRateLimiterLimitedFallback {
这个类是干啥用的？

2023-02-16 02:32 UTC, lingxiao-wu commented on spring-cloud-starter-tencent-polaris-ratelimit/src/test/java/com/tencent/cloud/polaris/ratelimit/filter/JsonPolarisRateLimiterLimitedFallback.java
> +public class JsonPolarisRateLimiterLimitedFallback implements PolarisRateLimiterLimitedFallback {
在QuotaCheckReactiveFilterTest和QuotaCheckServletFilterTest验证自定义的SPI是否生效的

2023-02-16 02:33 UTC, lepdou commented on spring-cloud-starter-tencent-polaris-ratelimit/src/test/java/com/tencent/cloud/polaris/ratelimit/filter/JsonPolarisRateLimiterLimitedFallback.java
> +public class JsonPolarisRateLimiterLimitedFallback implements PolarisRateLimiterLimitedFallback {
奥奥，在test目录下

2023-02-16 02:36 UTC, lepdou commented
@lingxiao-wu CLA 签名一下呢

2023-02-16 02:58 UTC, lingxiao-wu commented
> @lingxiao-wu CLA 签名一下呢

![image](https://user-images.githubusercontent.com/51630311/219256561-2f297023-8991-4227-a681-bb475f4d58e9.png)
我签署过了，这里说没签署是因为我账号名称和代码里的不一致吗

2023-02-16 06:55 UTC, SkyeBeFreeman commented
> > @lingxiao-wu CLA 签名一下呢
> 
> ![image](https://user-images.githubusercontent.com/51630311/219256561-2f297023-8991-4227-a681-bb475f4d58e9.png) 我签署过了，这里说没签署是因为我账号名称和代码里的不一致吗

有可能

2023-02-21 07:40 UTC, SkyeBeFreeman approved these changes

2023-02-21 07:41 UTC, merged

2023-02-21 09:36 UTC, SkyeBeFreeman commented
@lingxiao-wu 是否有空提交到2022和2020分支呢？