feature:add polaris circuit breaker support
Tencent/spring-cloud-tencent pull request #875
Opened 2023-03-03 02:39 UTC by ShanyouYu-Sean

## PR Type

Feature

## Describe what this PR does for and how you did.

add polaris circuit breaker support

## Adding the issue link (#xxx) if possible.

#678

## Note

## Checklist

- [ ] Add information of this PR to CHANGELOG.md in root of project.
- [ ] Add documentation in javadoc or comment below the PR if necessary.

## Checklist (Optional)

- [ ] Will pull request to branch of 2020.0.
- [ ] Will pull request to branch of 2022.0.

2023-03-03 05:09 UTC, SkyeBeFreeman requested changes

2023-03-03 05:09 UTC, SkyeBeFreeman commented on spring-cloud-tencent-examples/polaris-circuitbreaker-example/polaris-circuitbreaker-callee-service/src/main/resources/bootstrap.yml
> +      address: grpc://127.0.0.1:8091
这里IP地址不做修改，为体验版环境

2023-03-03 05:09 UTC, SkyeBeFreeman commented on spring-cloud-tencent-examples/polaris-circuitbreaker-example/polaris-circuitbreaker-callee-service2/src/main/resources/bootstrap.yml
> +      address: grpc://127.0.0.1:8091
这里IP地址不做修改，为体验版环境

2023-03-03 05:09 UTC, SkyeBeFreeman commented on spring-cloud-tencent-examples/polaris-circuitbreaker-example/polaris-circuitbreaker-feign-example/src/main/resources/bootstrap.yml
> +      address: grpc://127.0.0.1:8091
这里IP地址改为体验版环境

2023-03-03 05:09 UTC, SkyeBeFreeman commented on spring-cloud-tencent-examples/polaris-circuitbreaker-example/polaris-circuitbreaker-gateway-example/src/main/resources/bootstrap.yml
> +      address: grpc://127.0.0.1:8091
这里IP地址改为体验版环境

2023-03-03 05:09 UTC, SkyeBeFreeman commented on spring-cloud-tencent-examples/polaris-circuitbreaker-example/polaris-circuitbreaker-resttemplate-example/src/main/resources/bootstrap.yml
> +      address: grpc://127.0.0.1:8091
这里IP地址改为体验版环境

2023-03-03 05:09 UTC, SkyeBeFreeman commented on spring-cloud-tencent-examples/polaris-circuitbreaker-example/polaris-circuitbreaker-webclient-example/src/main/resources/bootstrap.yml
> +      address: grpc://127.0.0.1:8091
这里IP地址改为体验版环境

2023-03-03 05:10 UTC, SkyeBeFreeman commented
添加单测，使 GitHub Action 通过。

2023-03-03 08:51 UTC, andrewshan commented on spring-cloud-starter-tencent-polaris-circuitbreaker/src/main/java/com/tencent/cloud/polaris/circuitbreaker/PolarisCircuitBreaker.java
> +	public PolarisCircuitBreaker(String sourceNamespace, String sourceService, String namespace, String service, String method, CircuitBreakAPI circuitBreakAPI) {
String sourceNamespace, String sourceService, String namespace, String service, String method,

这几个参数，看看能不能封装成一个对象？

2023-03-03 08:53 UTC, andrewshan commented on spring-cloud-starter-tencent-polaris-circuitbreaker/src/main/java/com/tencent/cloud/polaris/circuitbreaker/PolarisCircuitBreaker.java
> +			LOGGER.debug("PolarisCircuitBreaker CallAbortedException: {}", e.getMessage());
这种应该打warn日志？

2023-03-03 08:55 UTC, andrewshan commented on spring-cloud-starter-tencent-polaris-circuitbreaker/src/main/java/com/tencent/cloud/polaris/circuitbreaker/ReactivePolarisCircuitBreaker.java
> +	public ReactivePolarisCircuitBreaker(String sourceNamespace, String sourceService, String namespace, String service, String method, CircuitBreakAPI circuitBreakAPI) {
String sourceNamespace, String sourceService, String namespace, String service, String method,
==
封装成对象，同上

2023-03-03 09:03 UTC, andrewshan requested changes
如果同时加了spring-retry和polaris-circuitbreaker，会怎么选择使用哪一个？

2023-03-03 09:45 UTC, ShanyouYu-Sean commented on spring-cloud-starter-tencent-polaris-circuitbreaker/src/main/java/com/tencent/cloud/polaris/circuitbreaker/PolarisCircuitBreaker.java
> +			LOGGER.debug("PolarisCircuitBreaker CallAbortedException: {}", e.getMessage());
@andrewshan 确认要打warn吗？这里我看Resilience4J都没有打日志

2023-03-06 02:43 UTC, ShanyouYu-Sean commented
> 如果同时加了spring-retry和polaris-circuitbreaker，会怎么选择使用哪一个？

会使用polaris-circuitbreaker

2023-03-06 03:47 UTC, andrewshan commented on spring-cloud-starter-tencent-polaris-circuitbreaker/src/main/java/com/tencent/cloud/polaris/circuitbreaker/PolarisCircuitBreaker.java
> +			LOGGER.debug("PolarisCircuitBreaker CallAbortedException: {}", e.getMessage());
那先这样吧

2023-03-06 03:48 UTC, andrewshan approved these changes
LGTM

2023-03-06 03:50 UTC, SkyeBeFreeman approved these changes
LGTM.

2023-03-06 03:51 UTC, merged