Feat issue 818
Tencent/spring-cloud-tencent pull request #924
Opened 2023-03-29 02:47 UTC by chuntaojun

## PR Type

## Describe what this PR does for and how you did.

## Adding the issue link (#xxx) if possible.

## Note

## Checklist

- [ ] Add information of this PR to CHANGELOG.md in root of project.
- [ ] Add documentation in javadoc or comment below the PR if necessary.

## Checklist (Optional)

- [ ] Will pull request to branch of 2020.0.
- [ ] Will pull request to branch of 2022.0.

2023-03-31 03:20 UTC, SkyeBeFreeman requested changes
添加CHANGELOG

2023-03-31 03:20 UTC, SkyeBeFreeman commented on spring-cloud-starter-tencent-polaris-circuitbreaker/src/main/java/com/tencent/cloud/polaris/circuitbreaker/util/PolarisCircuitBreakerUtils.java
> +			LOG.error("[CircuitBreaker]");
建议加一下ex本身的异常信息

2023-03-31 03:20 UTC, SkyeBeFreeman commented on spring-cloud-tencent-examples/polaris-circuitbreaker-example/polaris-circuitbreaker-callee-service/src/main/resources/bootstrap.yml
> +      address: grpc://127.0.0.1:8091
不改动体验集群IP

2023-03-31 03:20 UTC, SkyeBeFreeman commented on spring-cloud-tencent-examples/polaris-circuitbreaker-example/polaris-circuitbreaker-callee-service2/src/main/resources/bootstrap.yml
> +      address: grpc://127.0.0.1:8091
不改动体验集群IP

2023-03-31 03:20 UTC, SkyeBeFreeman commented on spring-cloud-tencent-examples/polaris-circuitbreaker-example/polaris-circuitbreaker-feign-example/src/main/resources/bootstrap.yml
> +      address: grpc://127.0.0.1:8091
不改动体验集群IP

2023-03-31 03:20 UTC, SkyeBeFreeman commented on spring-cloud-tencent-examples/polaris-circuitbreaker-example/polaris-circuitbreaker-gateway-example/src/main/resources/bootstrap.yml
> +      address: grpc://127.0.0.1:8091
不改动体验集群IP

2023-03-31 03:20 UTC, SkyeBeFreeman commented on spring-cloud-tencent-examples/polaris-circuitbreaker-example/polaris-circuitbreaker-resttemplate-example/src/main/resources/bootstrap.yml
> +      address: grpc://127.0.0.1:8091
不改动体验集群IP

2023-03-31 03:20 UTC, SkyeBeFreeman commented on spring-cloud-tencent-examples/polaris-circuitbreaker-example/polaris-circuitbreaker-webclient-example/src/main/resources/bootstrap.yml
> +      address: grpc://127.0.0.1:8091
不改动体验集群IP

2023-03-31 03:20 UTC, SkyeBeFreeman commented on spring-cloud-tencent-examples/polaris-gateway-example/gateway-callee-service/src/main/resources/bootstrap.yml
> +      address: grpc://127.0.0.1:8091
不改动体验集群IP

2023-03-31 03:20 UTC, SkyeBeFreeman commented on spring-cloud-tencent-examples/polaris-gateway-example/gateway-callee-service2/src/main/resources/bootstrap.yml
> +      address: grpc://127.0.0.1:8091
不改动体验集群IP

2023-03-31 03:20 UTC, SkyeBeFreeman commented on spring-cloud-tencent-examples/polaris-gateway-example/gateway-scg-service/src/main/resources/bootstrap.yml
> +      address: grpc://127.0.0.1:8091
不改动体验集群IP

2023-03-31 03:20 UTC, SkyeBeFreeman commented on spring-cloud-tencent-rpc-enhancement/src/main/java/com/tencent/cloud/rpc/enhancement/AbstractPolarisReporterAdapter.java
> +	public static String convertLabel(String label) {
放在common包里面的工具类吧

2023-03-31 03:20 UTC, SkyeBeFreeman commented on spring-cloud-tencent-rpc-enhancement/src/main/java/com/tencent/cloud/rpc/enhancement/resttemplate/EnhancedRestTemplateReporter.java
> +	private static RetStatus getRetStatusFromRequest(ClientHttpResponse response, RetStatus defaultVal) {
和`SuccessPolarisReporter`里面的一样吗？如果一样的话，将这两个类抽出来一个公共abstract类呗？

2023-03-31 03:20 UTC, SkyeBeFreeman commented on spring-cloud-tencent-rpc-enhancement/src/main/java/com/tencent/cloud/rpc/enhancement/scg/EnhancedPolarisHttpClient.java
> +			consumerAPI.updateServiceCallResult(result);
是否需要try-catch？

2023-03-31 07:01 UTC, SkyeBeFreeman requested changes

2023-03-31 07:01 UTC, SkyeBeFreeman commented on spring-cloud-tencent-examples/polaris-router-grayrelease-example/README-zh.md
> +   - 北极星服务端地址：polaris_address=grpc://183.47.111.80:8091
这里说清楚引入的北极星地址吧，监控和服务端地址不一样了

2023-03-31 07:08 UTC, andrewshan commented on CHANGELOG.md
> +- - [feat:support webclient and gateway report call metrics](https://github.com/Tencent/spring-cloud-tencent/pull/924)
这里是不是多了个-？

2023-03-31 07:10 UTC, andrewshan requested changes
文档格式未对齐

2023-03-31 09:48 UTC, SkyeBeFreeman requested changes
需要补充单测

2023-04-04 03:14 UTC, SkyeBeFreeman approved these changes

2023-04-04 03:19 UTC, merged