Dev
Tencent/spring-cloud-tencent pull request #983
Opened 2023-04-28 20:05 UTC by youtaqiu

## PR Type

Feature.

## Describe what this PR does for and how you did.

support reactive discovery clinet health Indicator.

## Note

## Checklist

- [ ] Add information of this PR to CHANGELOG.md in root of project.
- [ ] Add documentation in javadoc or comment below the PR if necessary.

## Checklist (Optional)

- [ ] Will pull request to branch of 2021.0.
- [ ] Will pull request to branch of 2022.0.

2023-04-29 13:15 UTC, SkyeBeFreeman requested changes

2023-04-29 13:15 UTC, SkyeBeFreeman commented on CHANGELOG.md
> +- [style: update ReactiveDiscoveryClient description.](https://github.com/youtaqiu/spring-cloud-tencent/commit/f31d720682a2d3507833c3420e8bfd3653574d38)
直接替换为PR链接，可以参考https://github.com/Tencent/spring-cloud-tencent/blob/2021.0/changes/changes-1.11.0.md

2023-04-29 14:35 UTC, youtaqiu commented on CHANGELOG.md
> +- [style: update ReactiveDiscoveryClient description.](https://github.com/youtaqiu/spring-cloud-tencent/commit/f31d720682a2d3507833c3420e8bfd3653574d38)
已修改

2023-04-30 05:12 UTC, SkyeBeFreeman requested changes

2023-04-30 05:12 UTC, SkyeBeFreeman commented on CHANGELOG.md
> +- [feature: support reactive discovery client health indicator.](https://github.com/Tencent/spring-cloud-tencent/pull/983)
只留feature这一行即可

2023-04-30 06:23 UTC, youtaqiu commented
好的发自我的 iPhone在 2023年4月30日，13:12，Haotian Zhang ***@***.***> 写道：﻿
@SkyeBeFreeman requested changes on this pull request.



In CHANGELOG.md:
> @@ -1,3 +1,6 @@
 # Change Log
 ---
 
+- [style: update ReactiveDiscoveryClient description.](https://github.com/Tencent/spring-cloud-tencent/pull/983)
+- [test: polarisReactiveDiscoveryClientHealthIndicator test.](https://github.com/Tencent/spring-cloud-tencent/pull/983)
+- [feature: support reactive discovery client health indicator.](https://github.com/Tencent/spring-cloud-tencent/pull/983)

只留feature这一行即可

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-04-30 06:28 UTC, youtaqiu commented
改好了。发自我的 iPhone在 2023年4月30日，13:12，Haotian Zhang ***@***.***> 写道：﻿
@SkyeBeFreeman requested changes on this pull request.



In CHANGELOG.md:
> @@ -1,3 +1,6 @@
 # Change Log
 ---
 
+- [style: update ReactiveDiscoveryClient description.](https://github.com/Tencent/spring-cloud-tencent/pull/983)
+- [test: polarisReactiveDiscoveryClientHealthIndicator test.](https://github.com/Tencent/spring-cloud-tencent/pull/983)
+- [feature: support reactive discovery client health indicator.](https://github.com/Tencent/spring-cloud-tencent/pull/983)

只留feature这一行即可

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-04-30 07:58 UTC, SkyeBeFreeman submitted a review, later dismissed
LGTM.

2023-05-02 03:49 UTC, SkyeBeFreeman approved these changes
LGTM.

2023-05-02 03:50 UTC, merged

2023-05-02 03:50 UTC, SkyeBeFreeman commented
@youtaqiu 是否方便提交到2020和2022分支呢？